## for AWS Exam Discusstion Extract

In [2]:
import time
import re
import os
import platform
import pandas as pd
from datetime import datetime, timedelta

import pyautogui

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager    # 크롬 드라이버 자동 업데이트

from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver import ActionChains

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from bs4 import BeautifulSoup

from random import *
from pathlib import Path
from dateutil import parser

In [3]:
def set_chrome_driver():
    #if platform.system() == "Darwin":
    #    service = Service(executable_path=r'./chromedriver')
    #elif platform.system() == "Windows":
    #    service = Service(executable_path=r'c:/temp/chromedriver.exe')
    
    # Setup options
    options = webdriver.ChromeOptions()
    options.add_argument("disable-infobars")    # 정보 표시줄 사용 안함
    options.add_argument("disable-extensions")    # 확장 사용 안함
    options.add_argument("disable-gpu")    # GPU 사용 안함
    # options.add_argument('headless') # 해드리스 사용
    # options.add_argument('start-maximized') # 시작시 전체 화면
    options.add_argument('--no-sandbox')
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--lang=kr')  # set your language here
    userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)s Chrome/92.0.4515.131 Safari/537.36"
    options.add_argument(f"user-agent={userAgent}")

    options.add_experimental_option('excludeSwitches', ['enable-logging'])  # 불필요한 에러 메시지 제거
    options.add_experimental_option("detach", True)     # 브라우저 꺼짐 방지 코드
    
    # Selenium 4.0 -- load webdriver
    try:
        # service = Service(ChromeDriverManager().install())    # CDM 설치 및 사용
        # driver = webdriver.Chrome(service=service, options=options)
        
        driver_path = ChromeDriverManager().install()
        correct_driver_path = os.path.join(os.path.dirname(driver_path), "chromedriver.exe")
        driver = webdriver.Chrome(service=Service(executable_path=correct_driver_path), options=options)

    except Exception as e:
        print(e)
        return
    
    driver.set_window_size(1500, driver.get_window_rect()["height"])
    # driver.set_window_size(1400, 1040)
    
    return driver

In [4]:
driver = set_chrome_driver()

discuss_id = 169071
discuss_url = f"https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id={discuss_id}"

driver.execute_script("window.open()");
driver.switch_to.window(driver.window_handles[1]);
driver.get(discuss_url)
time.sleep(1)

html = driver.page_source
bs = BeautifulSoup(html, 'html.parser')

# remove_discuss_element(driver)

bs

<html><head></head><body><div class="container outer-discussion-container">
<div class="row">
<div class="comments-container p-2 w-100">
<!-- New comment start -->
<div class="create-comment-base d-print-none">
<div class="new-comment-box mt-2" data-discussion-id="169071" data-linked-id="" data-linked-to="question" data-title="Exam AWS Certified DevOps Engineer - Professional DOP-C02 topic 1 question 363 discussion">
<form>
<div class="choice-vote-box">
<span class="chosen-answer-title">Chosen Answer:</span>
<span class="vote-checkboxes custom-checkbox">
</span>
<br/>
<span class="voting-comment-help">
						This is a voting comment<span class="voting-comment-brackets" style="display: none;"> (<a class="voting-comment-questionmark" href="javascript:void(0)">?</a>)</span>. <span class="switch-to-simple-comment-wrap" style="display: inline-block;">You can switch to a <a class="switch-to-simple-comment-btn" href="javascript:void(0)">simple comment</a>.</span> <!-- test1 -->It is better to Upvote an existing comment if you don't have anything to add.
					</span>
</div>
<div class="non-voting-comment-box">
<span class="voting-comment-help">
						Switch to a <a class="switch-to-voting-comment-btn" href="javascript:void(0)" id="votinglink" onclick="console.log('votinglink');">voting comment</a><!-- test2 -->
<span class="badge badge-warning">New</span>
</span>
</div>
<textarea class="form-control p-1 new-comment-textarea" placeholder="Type your comment..."></textarea>
</form>
<div class="create-comment-control align-right">
<a class="btn btn-link btn-sm comment-submit-button" href="#">Submit</a>
<a class="btn btn-link btn-sm comment-cancel-button" href="#">Cancel</a>
</div>
</div>
</div>
<!-- New comment end -->
<div class="discussion-container">
<!-- single_comment.html -->
<div class="media comment-container" data-comment-id="1395712" id="comment-1395712">
<a class="minimize-comment comment-toggle" href="#">
<i class="fa fa-minus-square-o mr-2 mt-1"></i>
</a>
<a class="maximize-comment comment-toggle" href="#">
<i class="fa fa-plus-square-o mr-2 mt-1"></i>
</a>
<div class="media-body">
<div class="comment-head">
<i class="fa fa-user mr-1 mt-1"></i>
<a href="/user/2b80c69/">
<h5 class="mt-0 mb-0 align-middle d-inline-block comment-username">
				2b80c69
			</h5>
</a>
<span class="comment-date align-middle" title="Fri 14 Mar 2025 21:20">
			1 week ago
		</span>
</div>
<div class="comment-body comment-toggled">
<div class="comment-selected-answers badge badge-warning">Selected Answer: <span><strong>A</strong></span></div>
<div class="comment-content">AWS Config has elb-waf-enabled managed rule which solves the problem in a most operationally efficient manner.
Not B coz, it focus more on sending notifications which is not the purpose of the question
Not C &amp; D coz, it has drift detection, which is again not the purpose of the question</div>
<div class="comment-control">
<span class="comment-control-buttons d-print-none">
<a class="comment-upvote requires-login" href="#" title="Upvote"><i class="fa fa-thumbs-up"></i></a>
<a class="ml-2 comment-reply-to requires-login" href="#" title="Reply"><i class="fa fa-reply"></i></a>
<a class="ml-2 comment-flag-report requires-login" href="#" title="Report"><i class="fa fa-flag"></i></a>
</span>
<span class="ml-2 upvote-text">
				upvoted <span class="upvote-count">1</span> times
			</span>
<span class="comment-control-error ml-2"></span>
</div>
<div class="new-comment-box-container mt-2">
</div>
<div class="comment-replies">
<!-- Nesting start -->
<!-- Nesting end -->
</div>
</div>
<div class="comment-ellipsis comment-toggled">
		...
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- Discussion end -->
<script type="text/javascript">
function eventFire(el, etype){
  if (el.fireEvent) {
    el.fireEvent('on' + etype);
  } else {
    var evObj = document.createEvent('Events');
    evObj.initEvent(etype, true, false);
    el.dispatchEvent(evObj);
  }
	const checkboxes = document.querySelectorAll('.vote-checkboxes input')
	if(checkboxes.length < 1){
		const switchToSimpleCommentWrap = document.querySelectorAll('.switch-to-simple-comment-wrap')
		const votingCommentBrackets = document.querySelectorAll('.voting-comment-brackets')
		switchToSimpleCommentWrap.forEach((item)=> item.style.display = 'inline-block')
		votingCommentBrackets.forEach((item)=> item.style.display = 'none')
	}
  console.log(etype);
}
function doVotingClick() {
	eventFire(document.getElementById('votinglink'), 'click');
}

//doVotingClick();
setTimeout(doVotingClick, 200);
</script></body></html>

In [5]:
# 모든 <script> 태그 제거
for script in bs.find_all("script"):
    script.extract()
bs

<html><head></head><body><div class="container outer-discussion-container">
<div class="row">
<div class="comments-container p-2 w-100">
<!-- New comment start -->
<div class="create-comment-base d-print-none">
<div class="new-comment-box mt-2" data-discussion-id="169071" data-linked-id="" data-linked-to="question" data-title="Exam AWS Certified DevOps Engineer - Professional DOP-C02 topic 1 question 363 discussion">
<form>
<div class="choice-vote-box">
<span class="chosen-answer-title">Chosen Answer:</span>
<span class="vote-checkboxes custom-checkbox">
</span>
<br/>
<span class="voting-comment-help">
						This is a voting comment<span class="voting-comment-brackets" style="display: none;"> (<a class="voting-comment-questionmark" href="javascript:void(0)">?</a>)</span>. <span class="switch-to-simple-comment-wrap" style="display: inline-block;">You can switch to a <a class="switch-to-simple-comment-btn" href="javascript:void(0)">simple comment</a>.</span> <!-- test1 -->It is better to Upvote an existing comment if you don't have anything to add.
					</span>
</div>
<div class="non-voting-comment-box">
<span class="voting-comment-help">
						Switch to a <a class="switch-to-voting-comment-btn" href="javascript:void(0)" id="votinglink" onclick="console.log('votinglink');">voting comment</a><!-- test2 -->
<span class="badge badge-warning">New</span>
</span>
</div>
<textarea class="form-control p-1 new-comment-textarea" placeholder="Type your comment..."></textarea>
</form>
<div class="create-comment-control align-right">
<a class="btn btn-link btn-sm comment-submit-button" href="#">Submit</a>
<a class="btn btn-link btn-sm comment-cancel-button" href="#">Cancel</a>
</div>
</div>
</div>
<!-- New comment end -->
<div class="discussion-container">
<!-- single_comment.html -->
<div class="media comment-container" data-comment-id="1395712" id="comment-1395712">
<a class="minimize-comment comment-toggle" href="#">
<i class="fa fa-minus-square-o mr-2 mt-1"></i>
</a>
<a class="maximize-comment comment-toggle" href="#">
<i class="fa fa-plus-square-o mr-2 mt-1"></i>
</a>
<div class="media-body">
<div class="comment-head">
<i class="fa fa-user mr-1 mt-1"></i>
<a href="/user/2b80c69/">
<h5 class="mt-0 mb-0 align-middle d-inline-block comment-username">
				2b80c69
			</h5>
</a>
<span class="comment-date align-middle" title="Fri 14 Mar 2025 21:20">
			1 week ago
		</span>
</div>
<div class="comment-body comment-toggled">
<div class="comment-selected-answers badge badge-warning">Selected Answer: <span><strong>A</strong></span></div>
<div class="comment-content">AWS Config has elb-waf-enabled managed rule which solves the problem in a most operationally efficient manner.
Not B coz, it focus more on sending notifications which is not the purpose of the question
Not C &amp; D coz, it has drift detection, which is again not the purpose of the question</div>
<div class="comment-control">
<span class="comment-control-buttons d-print-none">
<a class="comment-upvote requires-login" href="#" title="Upvote"><i class="fa fa-thumbs-up"></i></a>
<a class="ml-2 comment-reply-to requires-login" href="#" title="Reply"><i class="fa fa-reply"></i></a>
<a class="ml-2 comment-flag-report requires-login" href="#" title="Report"><i class="fa fa-flag"></i></a>
</span>
<span class="ml-2 upvote-text">
				upvoted <span class="upvote-count">1</span> times
			</span>
<span class="comment-control-error ml-2"></span>
</div>
<div class="new-comment-box-container mt-2">
</div>
<div class="comment-replies">
<!-- Nesting start -->
<!-- Nesting end -->
</div>
</div>
<div class="comment-ellipsis comment-toggled">
		...
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- Discussion end -->
</body></html>

In [7]:
div_discuss = bs.find_all("div", {"class": "container outer-discussion-container"})[0]

comment_spans = bs.find_all('span', class_='comment-date')
for comment_span in comment_spans:
    title = comment_span.get('title')
    if title:
        kst_time = parser.parse(str(title).replace("midnight", "12:00 a.m.").replace("noon", "12:00 p.m.")) + timedelta(hours=9)
        comment_span.string = kst_time.strftime("%Y-%m-%d %H:%M")

div = bs.find('div', attrs={'class': 'container outer-discussion-container'})

div_discuss.contents = [BeautifulSoup(div.decode_contents(), 'html.parser')]
discussion_en = div.decode_contents()

new_html = f"""
<!DOCTYPE html><html lang="ko">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>

    <title>Exam Topics Discussion</title>
</head>
<body>
    <div>Comments</div>
    {str(bs)}
</body>
</html>
"""

print(new_html)

<!DOCTYPE html><html lang="ko">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>

    <title>Exam Topics Discussion</title>
</head>
<body>
    <div>Comments</div>
    <html><head></head><body><div class="container outer-discussion-container">
<div class="row">
<div class="comments-container p-2 w-100">
<!-- New comment start -->
<div class="create-comment-base d-print-none">
<div class="new-comment-box mt-2" data-discussion-id="169071" data-linked-id="" data-linked-to="question" data-title="Exam AWS Certified DevOps Engineer - Professional DOP-C02 topic 1 question 363 discussion">
<form>
<div class="choice-vote-box">
<span class="chosen-answer-title">Chosen Answer:</span>
<span class="vote-checkboxes custom-checkbox">
</span>
<br/>
<span class="voting-comment-help">
						This is a voting comment<span class="voting-comment-brackets" style="display: none;"> (<a class="voting-comment-questionmark" href="javascript:void(0)">?</a>)</span>. <span class="switch-to-simple-comment-wrap" style="display: inline-block;">You can switch to a <a class="switch-to-simple-comment-btn" href="javascript:void(0)">simple comment</a>.</span> <!-- test1 -->It is better to Upvote an existing comment if you don't have anything to add.
					</span>
</div>
<div class="non-voting-comment-box">
<span class="voting-comment-help">
						Switch to a <a class="switch-to-voting-comment-btn" href="javascript:void(0)" id="votinglink" onclick="console.log('votinglink');">voting comment</a><!-- test2 -->
<span class="badge badge-warning">New</span>
</span>
</div>
<textarea class="form-control p-1 new-comment-textarea" placeholder="Type your comment..."></textarea>
</form>
<div class="create-comment-control align-right">
<a class="btn btn-link btn-sm comment-submit-button" href="#">Submit</a>
<a class="btn btn-link btn-sm comment-cancel-button" href="#">Cancel</a>
</div>
</div>
</div>
<!-- New comment end -->
<div class="discussion-container">
<!-- single_comment.html -->
<div class="media comment-container" data-comment-id="1395712" id="comment-1395712">
<a class="minimize-comment comment-toggle" href="#">
<i class="fa fa-minus-square-o mr-2 mt-1"></i>
</a>
<a class="maximize-comment comment-toggle" href="#">
<i class="fa fa-plus-square-o mr-2 mt-1"></i>
</a>
<div class="media-body">
<div class="comment-head">
<i class="fa fa-user mr-1 mt-1"></i>
<a href="/user/2b80c69/">
<h5 class="mt-0 mb-0 align-middle d-inline-block comment-username">
				2b80c69
			</h5>
</a>
<span class="comment-date align-middle" title="Fri 14 Mar 2025 21:20">2025-03-15 06:20</span>
</div>
<div class="comment-body comment-toggled">
<div class="comment-selected-answers badge badge-warning">Selected Answer: <span><strong>A</strong></span></div>
<div class="comment-content">AWS Config has elb-waf-enabled managed rule which solves the problem in a most operationally efficient manner.
Not B coz, it focus more on sending notifications which is not the purpose of the question
Not C &amp; D coz, it has drift detection, which is again not the purpose of the question</div>
<div class="comment-control">
<span class="comment-control-buttons d-print-none">
<a class="comment-upvote requires-login" href="#" title="Upvote"><i class="fa fa-thumbs-up"></i></a>
<a class="ml-2 comment-reply-to requires-login" href="#" title="Reply"><i class="fa fa-reply"></i></a>
<a class="ml-2 comment-flag-report requires-login" href="#" title="Report"><i class="fa fa-flag"></i></a>
</span>
<span class="ml-2 upvote-text">
				upvoted <span class="upvote-count">1</span> times
			</span>
<span class="comment-control-error ml-2"></span>
</div>
<div class="new-comment-box-container mt-2">
</div>
<div class="comment-replies">
<!-- Nesting start -->
<!-- Nesting end -->
</div>
</div>
<div class="comment-ellipsis comment-toggled">
		...
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- Discussion end -->
</body></html>
</body>
</html>

In [8]:
driver.quit()

In [ ]:
bs = BeautifulSoup(driver.page_source, 'html.parser')

# 모든 <script> 태그 제거
for script in bs.find_all("script"):
    script.extract()

In [75]:
    print(driver.title + "-" + str(1))
    bs = BeautifulSoup(driver.page_source, 'html.parser')
    div_card = bs.find_all("div", {"class": "container-fluid discussion-list"})
    a = bs.find_all("a", {"class": "discussion-link"})
    span = bs.find_all("span", {"class": "recent-post-time"})
    
    found = False
    for i in range(len(a)):
        if found == True: break
        
        last_post = parser.parse(str(span[i*2+1]["title"]).replace("midnight", "12:00 a.m.").replace("noon", "12:00 p.m."))
        split_text = str(a[i].text.strip()).split()

        question = ' '.join(split_text[:5])
        number = split_text[5]
        discussion = split_text[6]
        did = str(a[i]["href"]).split('/')[4].split('-')[0]

        print(question+"\t"+str(number)+"\t"+discussion+"\t"+str(last_post)+"\t"+str(a[i]["href"])+"\t"+did+"\n")
        if (df['ExamType'] == question).any() and \
            (df['ExamNo'] == number).any() and \
            (df['DiscussNo'] == did).any():
            print("The values exist in the DataFrame.")
            if (df['LastPost'] == str(last_post)).any():
                print("Same value exists, exit")
                found = True
                break
            print(df.loc[(df['ExamType'] == question) & (df['ExamNo'] == number) & (df['DiscussNo'] == did), 'LastPost'], str(last_post))
            df.loc[(df['ExamType'] == question) & (df['ExamNo'] == number) & (df['DiscussNo'] == did), 'LastPost'] = str(last_post)
        else:
            print("The values do not exist in the DataFrame.")
            new_row = [{ 'ExamType': question, 'ExamNo': number, 'Discussion': discussion, 'LastPost': str(last_post),
                         'DiscussURL': a[i]["href"], 'DiscussNo': did }]
            df = pd.concat([df, pd.DataFrame(new_row)], ignore_index=True)

-1

## DataFrame Test

In [5]:
import pandas as pd

df = pd.read_csv('IsacaDiscuss.txt', delimiter='\t', encoding='utf-8', header=None,
                 names=['ExamType', 'ExamNo', 'DiscussNo', 'DataID', 'LastPost', 'DiscussURL'], index_col=False)
                 #names=['ExamType', 'ExamNo', 'DiscussNo', 'LastPost', 'DiscussURL'], index_col=False)
# df = df[df['ExamType'] == 'Exam AWS Certified Solutions Architect - Professional topic 1']
df

,ExamType,ExamNo,DiscussNo,DataID,LastPost,DiscussURL
0,Exam CISA topic 1,573,49537,818598,2023-11-25 06:22:00,/discussions/isaca/view/49537-exam-cisa-topic-...
1,Exam CISA topic 1,569,116483,818594,2023-11-25 05:51:00,/discussions/isaca/view/116483-exam-cisa-topic...
2,Exam CISA topic 1,567,116481,818592,2023-11-25 05:45:00,/discussions/isaca/view/116481-exam-cisa-topic...
3,Exam CISA topic 1,565,107842,818590,2023-11-25 05:40:00,/discussions/isaca/view/107842-exam-cisa-topic...
4,Exam CISA topic 1,560,80902,818585,2023-11-25 05:25:00,/discussions/isaca/view/80902-exam-cisa-topic-...
...,...,...,...,...,...,...
3596,Exam CISA topic 1,136,83776,818161,2022-09-27 13:22:00,/discussions/isaca/view/83776-exam-cisa-topic-...
3597,Exam CISA topic 1,108,83704,818133,2022-09-26 18:18:00,/discussions/isaca/view/83704-exam-cisa-topic-...
3598,Exam CISA topic 1,743,81027,818768,2022-09-22 18:48:00,/discussions/isaca/view/81027-exam-cisa-topic-...
3599,Exam CISA topic 1,335,80845,818360,2022-09-08 14:36:00,/discussions/isaca/view/80845-exam-cisa-topic-...
3600,Exam CISA topic 1,37,80455,818062,2022-09-06 02:03:00,/discussions/isaca/view/80455-exam-cisa-topic-...

In [6]:

df['ExamType'] = df['ExamType'].str.strip()
df['ExamNo'] = df['ExamNo'].astype(int)
df['DiscussNo'] = df['DiscussNo'].astype(int)
df['DataID'] = df['DataID'].astype(int)
df['LastPost'] = pd.to_datetime(df['LastPost'], format='%Y-%m-%d %H:%M')
df['DiscussURL'] = df['DiscussURL'].str.strip()

df.drop_duplicates(inplace=True)
df = df.sort_values(by=['LastPost', 'DiscussNo'], ascending=[False, False])
df

,ExamType,ExamNo,DiscussNo,DataID,LastPost,DiscussURL
0,Exam CISA topic 1,573,49537,818598,2023-11-25 06:22:00,/discussions/isaca/view/49537-exam-cisa-topic-...
1,Exam CISA topic 1,569,116483,818594,2023-11-25 05:51:00,/discussions/isaca/view/116483-exam-cisa-topic...
2,Exam CISA topic 1,567,116481,818592,2023-11-25 05:45:00,/discussions/isaca/view/116481-exam-cisa-topic...
3,Exam CISA topic 1,565,107842,818590,2023-11-25 05:40:00,/discussions/isaca/view/107842-exam-cisa-topic...
4,Exam CISA topic 1,560,80902,818585,2023-11-25 05:25:00,/discussions/isaca/view/80902-exam-cisa-topic-...
...,...,...,...,...,...,...
3596,Exam CISA topic 1,136,83776,818161,2022-09-27 13:22:00,/discussions/isaca/view/83776-exam-cisa-topic-...
3597,Exam CISA topic 1,108,83704,818133,2022-09-26 18:18:00,/discussions/isaca/view/83704-exam-cisa-topic-...
3598,Exam CISA topic 1,743,81027,818768,2022-09-22 18:48:00,/discussions/isaca/view/81027-exam-cisa-topic-...
3599,Exam CISA topic 1,335,80845,818360,2022-09-08 14:36:00,/discussions/isaca/view/80845-exam-cisa-topic-...
3600,Exam CISA topic 1,37,80455,818062,2022-09-06 02:03:00,/discussions/isaca/view/80455-exam-cisa-topic-...

In [17]:
#df['LastPost'][0]
row = df.iloc[0]
row['DataID']
#print(df.iloc[0])

818598

In [14]:
for index in range(len(df)-1, -1, -1):
    row = df.iloc[index]
    # Your processing logic goes here
    print(f"Processing row {index}:", row)

Processing row 3600: ExamType                                      Exam CISA topic 1
ExamNo                                                       37
DiscussNo                                                 80455
DataID                                                   818062
LastPost                                    2022-09-06 02:03:00
DiscussURL    /discussions/isaca/view/80455-exam-cisa-topic-...
Name: 3600, dtype: object
Processing row 3599: ExamType                                      Exam CISA topic 1
ExamNo                                                      335
DiscussNo                                                 80845
DataID                                                   818360
LastPost                                    2022-09-08 14:36:00
DiscussURL    /discussions/isaca/view/80845-exam-cisa-topic-...
Name: 3599, dtype: object
Processing row 3598: ExamType                                      Exam CISA topic 1
ExamNo                                                      743
DiscussNo                                                 81027
DataID                                                   818768
LastPost                                    2022-09-22 18:48:00
DiscussURL    /discussions/isaca/view/81027-exam-cisa-topic-...
Name: 3598, dtype: object
Processing row 3597: ExamType                                      Exam CISA topic 1
ExamNo                                                      108
DiscussNo                                                 83704
DataID                                                   818133
LastPost                                    2022-09-26 18:18:00
DiscussURL    /discussions/isaca/view/83704-exam-cisa-topic-...
Name: 3597, dtype: object
Processing row 3596: ExamType                                      Exam CISA topic 1
ExamNo                                                      136
DiscussNo                                                 83776
DataID                                                   818161
LastPost                                    2022-09-27 13:22:00
DiscussURL    /discussions/isaca/view/83776-exam-cisa-topic-...
Name: 3596, dtype: object
Processing row 3595: ExamType                                      Exam CISA topic 1
ExamNo                                                      339
DiscussNo                                                 84183
DataID                                                   818364
LastPost                                    2022-10-01 18:52:00
DiscussURL    /discussions/isaca/view/84183-exam-cisa-topic-...
Name: 3595, dtype: object
Processing row 3594: ExamType                                      Exam CISA topic 1
ExamNo                                                      421
DiscussNo                                                 84232
DataID                                                   818446
LastPost                                    2022-10-02 18:19:00
DiscussURL    /discussions/isaca/view/84232-exam-cisa-topic-...
Name: 3594, dtype: object
Processing row 3593: ExamType                                      Exam CISA topic 1
ExamNo                                                      488
DiscussNo                                                 84271
DataID                                                   818513
LastPost                                    2022-10-03 13:05:00
DiscussURL    /discussions/isaca/view/84271-exam-cisa-topic-...
Name: 3593, dtype: object
Processing row 3592: ExamType                                      Exam CISA topic 1
ExamNo                                                      548
DiscussNo                                                 84297
DataID                                                   818573
LastPost                                    2022-10-03 16:24:00
DiscussURL    /discussions/isaca/view/84297-exam-cisa-topic-...
Name: 3592, dtype: object
Processing row 3591: ExamType                                     Exam CRISC topic 1
ExamNo                                                      142
DiscussNo                                                 84370
DataID                                                        0
LastPost                                    2022-10-04 21:10:00
DiscussURL    /discussions/isaca/view/84370-exam-crisc-topic...
Name: 3591, dtype: object
Processing row 3590: ExamType                                      Exam CISM topic 1
ExamNo                                                     1613
DiscussNo                                                 63493
DataID                                                   786423
LastPost                                    2022-10-05 08:57:00
DiscussURL    /discussions/isaca/view/63493-exam-cism-topic-...
Name: 3590, dtype: object
Processing row 3589: ExamType                                      Exam CISM topic 1
ExamNo                                                     1320
DiscussNo                                                 21913
DataID                                                   786130
LastPost                                    2022-10-09 08:40:00
DiscussURL    /discussions/isaca/view/21913-exam-cism-topic-...
Name: 3589, dtype: object
Processing row 3588: ExamType                                      Exam CISA topic 1
ExamNo                                                      165
DiscussNo                                                 83897
DataID                                                   818190
LastPost                                    2022-10-09 14:02:00
DiscussURL    /discussions/isaca/view/83897-exam-cisa-topic-...
Name: 3588, dtype: object
Processing row 3587: ExamType                                     Exam CRISC topic 1
ExamNo                                                      436
DiscussNo                                                 49115
DataID                                                        0
LastPost                                    2022-10-29 16:59:00
DiscussURL    /discussions/isaca/view/49115-exam-crisc-topic...
Name: 3587, dtype: object
Processing row 3586: ExamType                                      Exam CISM topic 1
ExamNo                                                     1672
DiscussNo                                                 67872
DataID                                                   786482
LastPost                                    2022-11-06 10:53:00
DiscussURL    /discussions/isaca/view/67872-exam-cism-topic-...
Name: 3586, dtype: object
Processing row 3585: ExamType                                     Exam CGEIT topic 1
ExamNo                                                      253
DiscussNo                                                 87883
DataID                                                        0
LastPost                                    2022-11-18 10:56:00
DiscussURL    /discussions/isaca/view/87883-exam-cgeit-topic...
Name: 3585, dtype: object
Processing row 3584: ExamType                                     Exam CRISC topic 1
ExamNo                                                       24
DiscussNo                                                 83054
DataID                                                        0
LastPost                                    2022-11-28 17:22:00
DiscussURL    /discussions/isaca/view/83054-exam-crisc-topic...
Name: 3584, dtype: object
Processing row 3583: ExamType                                     Exam CRISC topic 1
ExamNo                                                       27
DiscussNo                                                  2548
DataID                                                        0
LastPost                                    2022-11-28 17:58:00
DiscussURL    /discussions/isaca/view/2548-exam-crisc-topic-...
Name: 3583, dtype: object
Processing row 3582: ExamType                                      Exam CISM topic 1
ExamNo                                                     1564
DiscussNo                                                 66132
DataID                                                   786374
LastPost                                    2022-11-29 10:21:00
DiscussURL    /discussions/isaca/view/66132-exam-cism-topic-...
Name: 3582, dtype: object
Processing row 3581: ExamType                                     Exam CDPSE topic 1
ExamNo                                                       15
DiscussNo                                                 89414
DataID                                                        0
LastPost                                    2022-11-30 16:38:00
DiscussURL    /discussions/isaca/view/89414-exam-cdpse-topic...
Name: 3581, dtype: object
Processing row 3580: ExamType                                     Exam CDPSE topic 1
ExamNo                                                       35
DiscussNo                                                 88076
DataID                                                        0
LastPost                                    2022-11-30 17:30:00
DiscussURL    /discussions/isaca/view/88076-exam-cdpse-topic...
Name: 3580, dtype: object
Processing row 3579: ExamType                                     Exam CDPSE topic 1
ExamNo                                                       92
DiscussNo                                                 89445
DataID                                                        0
LastPost                                    2022-11-30 21:49:00
DiscussURL    /discussions/isaca/view/89445-exam-cdpse-topic...
Name: 3579, dtype: object
Processing row 3578: ExamType                                     Exam CGEIT topic 1
ExamNo                                                      368
DiscussNo                                                 89580
DataID                                                        0
LastPost                                    2022-12-01 16:01:00
DiscussURL    /discussions/isaca/view/89580-exam-cgeit-topic...
Name: 3578, dtype: object
Processing row 3577: ExamType                                      Exam CISA topic 1
ExamNo                                                      791
DiscussNo                                                 91983
DataID                                                   818816
LastPost                                    2022-12-18 09:17:00
DiscussURL    /discussions/isaca/view/91983-exam-cisa-topic-...
Name: 3577, dtype: object
Processing row 3576: ExamType                                      Exam CISA topic 1
ExamNo                                                      690
DiscussNo                                                 85797
DataID                                                   818715
LastPost                                    2022-12-21 11:22:00
DiscussURL    /discussions/isaca/view/85797-exam-cisa-topic-...
Name: 3576, dtype: object
Processing row 3575: ExamType                                     Exam CGEIT topic 1
ExamNo                                                      229
DiscussNo                                                 59406
DataID                                                        0
LastPost                                    2022-12-25 23:38:00
DiscussURL    /discussions/isaca/view/59406-exam-cgeit-topic...
Name: 3575, dtype: object
Processing row 3574: ExamType                                      Exam CISA topic 1
ExamNo                                                      137
DiscussNo                                                 92944
DataID                                                   818162
LastPost                                    2022-12-27 08:28:00
DiscussURL    /discussions/isaca/view/92944-exam-cisa-topic-...
Name: 3574, dtype: object
Processing row 3573: ExamType                                      Exam CISM topic 1
ExamNo                                                     1627
DiscussNo                                                 30737
DataID                                                   786437
LastPost                                    2022-12-27 11:44:00
DiscussURL    /discussions/isaca/view/30737-exam-cism-topic-...
Name: 3573, dtype: object
Processing row 3572: ExamType                                     Exam CRISC topic 1
ExamNo                                                      147
DiscussNo                                                 51944
DataID                                                        0
LastPost                                    2022-12-27 19:10:00
DiscussURL    /discussions/isaca/view/51944-exam-crisc-topic...
Name: 3572, dtype: object
Processing row 3571: ExamType                                     Exam CRISC topic 1
ExamNo                                                      246
DiscussNo                                                 19976
DataID                                                        0
LastPost                                    2022-12-28 03:04:00
DiscussURL    /discussions/isaca/view/19976-exam-crisc-topic...
Name: 3571, dtype: object
Processing row 3570: ExamType                                      Exam CISA topic 1
ExamNo                                                     1275
DiscussNo                                                 52148
DataID                                                   751124
LastPost                                    2022-12-31 03:33:00
DiscussURL    /discussions/isaca/view/52148-exam-cisa-topic-...
Name: 3570, dtype: object
Processing row 3569: ExamType                                      Exam CISA topic 1
ExamNo                                                     3147
DiscussNo                                                 49232
DataID                                                   752996
LastPost                                    2022-12-31 13:29:00
DiscussURL    /discussions/isaca/view/49232-exam-cisa-topic-...
Name: 3569, dtype: object
Processing row 3568: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       59
DiscussNo                                                 93463
DataID                                                        0
LastPost                                    2023-01-01 03:26:00
DiscussURL    /discussions/isaca/view/93463-exam-cobit-2019-...
Name: 3568, dtype: object
Processing row 3567: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       62
DiscussNo                                                 93466
DataID                                                        0
LastPost                                    2023-01-01 04:24:00
DiscussURL    /discussions/isaca/view/93466-exam-cobit-2019-...
Name: 3567, dtype: object
Processing row 3566: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       74
DiscussNo                                                 93213
DataID                                                        0
LastPost                                    2023-01-01 05:56:00
DiscussURL    /discussions/isaca/view/93213-exam-cobit-2019-...
Name: 3566, dtype: object
Processing row 3565: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       75
DiscussNo                                                 93214
DataID                                                        0
LastPost                                    2023-01-01 05:59:00
DiscussURL    /discussions/isaca/view/93214-exam-cobit-2019-...
Name: 3565, dtype: object
Processing row 3564: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       79
DiscussNo                                                 93471
DataID                                                        0
LastPost                                    2023-01-01 06:06:00
DiscussURL    /discussions/isaca/view/93471-exam-cobit-2019-...
Name: 3564, dtype: object
Processing row 3563: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       84
DiscussNo                                                 93472
DataID                                                        0
LastPost                                    2023-01-01 06:15:00
DiscussURL    /discussions/isaca/view/93472-exam-cobit-2019-...
Name: 3563, dtype: object
Processing row 3562: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       87
DiscussNo                                                 93473
DataID                                                        0
LastPost                                    2023-01-01 06:25:00
DiscussURL    /discussions/isaca/view/93473-exam-cobit-2019-...
Name: 3562, dtype: object
Processing row 3561: ExamType                                      Exam CISA topic 1
ExamNo                                                      222
DiscussNo                                                 84321
DataID                                                   818247
LastPost                                    2023-01-01 20:48:00
DiscussURL    /discussions/isaca/view/84321-exam-cisa-topic-...
Name: 3561, dtype: object
Processing row 3560: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                      110
DiscussNo                                                 93572
DataID                                                        0
LastPost                                    2023-01-02 17:39:00
DiscussURL    /discussions/isaca/view/93572-exam-cobit-2019-...
Name: 3560, dtype: object
Processing row 3559: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                      118
DiscussNo                                                 93612
DataID                                                        0
LastPost                                    2023-01-02 23:54:00
DiscussURL    /discussions/isaca/view/93612-exam-cobit-2019-...
Name: 3559, dtype: object
Processing row 3558: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       35
DiscussNo                                                 93783
DataID                                                        0
LastPost                                    2023-01-04 03:46:00
DiscussURL    /discussions/isaca/view/93783-exam-cobit-2019-...
Name: 3558, dtype: object
Processing row 3557: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       36
DiscussNo                                                 93784
DataID                                                        0
LastPost                                    2023-01-04 03:54:00
DiscussURL    /discussions/isaca/view/93784-exam-cobit-2019-...
Name: 3557, dtype: object
Processing row 3556: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       48
DiscussNo                                                 93789
DataID                                                        0
LastPost                                    2023-01-04 05:43:00
DiscussURL    /discussions/isaca/view/93789-exam-cobit-2019-...
Name: 3556, dtype: object
Processing row 3555: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                       50
DiscussNo                                                 93792
DataID                                                        0
LastPost                                    2023-01-04 05:50:00
DiscussURL    /discussions/isaca/view/93792-exam-cobit-2019-...
Name: 3555, dtype: object
Processing row 3554: ExamType                                Exam COBIT 2019 topic 1
ExamNo                                                      122

In [9]:
# Update 'PostDate' to the maximum value within each group of 'Type' and 'No'
df['MaxDataID'] = df.groupby(['ExamType', 'ExamNo'])['DataID'].transform('max')
df['Chk'] = df.apply(lambda row: 1 if row['DataID'] == row['MaxDataID'] else 0, axis=1)
df = df.sort_values(['Chk', 'LastPost', 'DiscussNo'], ascending=[False, False, False]).drop(columns=['MaxDataID', 'Chk'])
# Save the modified DataFrame back to a CSV file
df.to_csv('modified_mydata.csv', index=False, sep='\t', encoding='utf-8', header=None)
df

,ExamType,ExamNo,DiscussNo,DataID,LastPost,DiscussURL
0,Exam CRISC topic 1,642,26685,0,2023-09-01 23:52:00,/discussions/isaca/view/26685-exam-crisc-topic...
1,Exam CRISC topic 1,641,47984,0,2023-09-01 23:42:00,/discussions/isaca/view/47984-exam-crisc-topic...
2,Exam CRISC topic 1,640,54258,0,2023-09-01 23:36:00,/discussions/isaca/view/54258-exam-crisc-topic...
3,Exam CRISC topic 1,639,30411,0,2023-09-01 23:26:00,/discussions/isaca/view/30411-exam-crisc-topic...
4,Exam CRISC topic 1,638,30167,0,2023-09-01 23:24:00,/discussions/isaca/view/30167-exam-crisc-topic...
...,...,...,...,...,...,...
5446,Exam CISM topic 1,327,28674,785137,2020-09-12 14:23:00,/discussions/isaca/view/28674-exam-cism-topic-...
5447,Exam CISA topic 1,775,30067,750624,2020-09-12 07:11:00,/discussions/isaca/view/30067-exam-cisa-topic-...
5448,Exam CISA topic 1,288,30880,750137,2020-09-08 20:37:00,/discussions/isaca/view/30880-exam-cisa-topic-...
5449,Exam CISA topic 1,827,28815,750676,2020-09-03 15:05:00,/discussions/isaca/view/28815-exam-cisa-topic-...
5450,Exam CISM topic 1,799,25608,467338,2020-07-13 15:09:00,/discussions/isaca/view/25608-exam-cism-topic-...

In [5]:
def sleep_random_sec(sec):
    for t in reversed(range(randint(1, sec))):
        print(str(t), end='', flush=True)
        time.sleep(1)
    print('')
    
def open_exam(driver, discuss_url):
    # sleep_random_sec(3)
    exam_url = 'https://www.examtopics.com' + discuss_url
    pattern = r'<div class="question-body mt-3 pt-3 border-top" data-id="([0-9]+)">'

    page = driver.get(exam_url)

    bs = BeautifulSoup(driver.page_source, 'html.parser')
    div_discuss = bs.find_all("div", {"class": "container outer-discussion-container"})
    while (len(div_discuss) <= 0):
        print("Waiting...")
        bs = BeautifulSoup(driver.page_source, 'html.parser')
        div_discuss = bs.find_all("div", {"class": "container outer-discussion-container"})
        if (driver.title == 'Error 404 (Not Found)!!1'):
            break
        winsound.PlaySound("SystemExclamation", winsound.SND_ALIAS)
        time.sleep(3)
    
    match = re.search(pattern, str(bs))
    if match:
        print(f'url={discuss_url}, data_id = {match.group(1)}')

    return

In [2]:
urls = [
   { 'url': '/discussions/amazon/view/24902-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27940-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/21792-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/24833-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/21962-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/21964-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/21830-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27839-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27840-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27837-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27838-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/27836-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/46358-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/25147-exam-aws-certified-database-specialty-topic-1-question-20/' },
   { 'url': '/discussions/amazon/view/22182-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/28085-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/5769-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/51220-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/60090-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/29771-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/24825-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/46600-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/74125-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/61148-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/48842-exam-aws-certified-database-specialty-topic-1-question-141/' },
   { 'url': '/discussions/amazon/view/36057-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/59990-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/46368-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/5176-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/13316-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/67692-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/67656-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/46963-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/46832-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/26323-exam-aws-certified-database-specialty-topic-1-question-56/' },
   { 'url': '/discussions/amazon/view/25815-exam-aws-certified-database-specialty-topic-1-question-31/' },
   { 'url': '/discussions/amazon/view/61159-exam-aws-certified-solutions-architect-associate-saa-c02/' },
   { 'url': '/discussions/amazon/view/25196-exam-aws-certified-database-specialty-topic-1-question-49/' },
   { 'url': '/discussions/amazon/view/25869-exam-aws-certified-database-specialty-topic-1-question-2/' },
   { 'url': '/discussions/amazon/view/26424-exam-aws-certified-database-specialty-topic-1-question-52/' },
   { 'url': '/discussions/amazon/view/25068-exam-aws-certified-database-specialty-topic-1-question-14/' },
   { 'url': '/discussions/amazon/view/26021-exam-aws-certified-database-specialty-topic-1-question-44/' },
   { 'url': '/discussions/amazon/view/5127-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/26592-exam-aws-certified-database-specialty-topic-1-question-63/' },
   { 'url': '/discussions/amazon/view/26231-exam-aws-certified-database-specialty-topic-1-question-29/' },
   { 'url': '/discussions/amazon/view/12853-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/8764-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/7627-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/5126-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/25620-exam-aws-certified-database-specialty-topic-1-question-46/' },
   { 'url': '/discussions/amazon/view/26803-exam-aws-certified-database-specialty-topic-1-question-53/' },
   { 'url': '/discussions/amazon/view/25599-exam-aws-certified-database-specialty-topic-1-question-32/' },
   { 'url': '/discussions/amazon/view/26774-exam-aws-certified-database-specialty-topic-1-question-61/' },
   { 'url': '/discussions/amazon/view/25725-exam-aws-certified-database-specialty-topic-1-question-39/' },
   { 'url': '/discussions/amazon/view/31126-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/25639-exam-aws-certified-database-specialty-topic-1-question-16/' },
   { 'url': '/discussions/amazon/view/5210-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/11802-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/28991-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/11453-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/25733-exam-aws-certified-database-specialty-topic-1-question-8/' },
   { 'url': '/discussions/amazon/view/12300-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/25203-exam-aws-certified-database-specialty-topic-1-question-60/' },
   { 'url': '/discussions/amazon/view/9895-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/19716-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/31264-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/12325-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/14891-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/53233-exam-aws-certified-solutions-architect-professional-topic-1/' },
   { 'url': '/discussions/amazon/view/12297-exam-aws-certified-solutions-architect-professional-topic-1/' },
]

driver = set_chrome_driver()

for i in range(len(urls)):
   #print(urls[i]['url'])
   open_exam(driver, urls[i]['url'])

driver.quit()

NameError: name 'set_chrome_driver' is not defined

In [6]:
urls = [
{ 'url': '/discussions/microsoft/view/62815-exam-az-900-topic-1-question-1-discussion/' },
{ 'url': '/discussions/microsoft/view/56934-exam-az-900-topic-1-question-2-discussion/' },
{ 'url': '/discussions/microsoft/view/56418-exam-az-900-topic-1-question-3-discussion/' },
{ 'url': '/discussions/microsoft/view/56881-exam-az-900-topic-1-question-4-discussion/' },
{ 'url': '/discussions/microsoft/view/56882-exam-az-900-topic-1-question-5-discussion/' },
{ 'url': '/discussions/microsoft/view/56559-exam-az-900-topic-1-question-6-discussion/' },
{ 'url': '/discussions/microsoft/view/56422-exam-az-900-topic-1-question-7-discussion/' },
{ 'url': '/discussions/microsoft/view/56761-exam-az-900-topic-1-question-8-discussion/' },
{ 'url': '/discussions/microsoft/view/62985-exam-az-900-topic-1-question-9-discussion/' },
{ 'url': '/discussions/microsoft/view/56453-exam-az-900-topic-1-question-10-discussion/' },
{ 'url': '/discussions/microsoft/view/56624-exam-az-900-topic-1-question-11-discussion/' },
{ 'url': '/discussions/microsoft/view/56625-exam-az-900-topic-1-question-12-discussion/' },
{ 'url': '/discussions/microsoft/view/56627-exam-az-900-topic-1-question-13-discussion/' },
{ 'url': '/discussions/microsoft/view/56918-exam-az-900-topic-1-question-14-discussion/' },
{ 'url': '/discussions/microsoft/view/56888-exam-az-900-topic-1-question-15-discussion/' },
{ 'url': '/discussions/microsoft/view/56892-exam-az-900-topic-1-question-16-discussion/' },
{ 'url': '/discussions/microsoft/view/56306-exam-az-900-topic-1-question-17-discussion/' },
{ 'url': '/discussions/microsoft/view/56893-exam-az-900-topic-1-question-18-discussion/' },
{ 'url': '/discussions/microsoft/view/56634-exam-az-900-topic-1-question-19-discussion/' },
{ 'url': '/discussions/microsoft/view/56636-exam-az-900-topic-1-question-20-discussion/' },
{ 'url': '/discussions/microsoft/view/56635-exam-az-900-topic-1-question-21-discussion/' },
{ 'url': '/discussions/microsoft/view/56637-exam-az-900-topic-1-question-22-discussion/' },
{ 'url': '/discussions/microsoft/view/56899-exam-az-900-topic-1-question-23-discussion/' },
{ 'url': '/discussions/microsoft/view/56826-exam-az-900-topic-1-question-24-discussion/' },
{ 'url': '/discussions/microsoft/view/56641-exam-az-900-topic-1-question-25-discussion/' },
{ 'url': '/discussions/microsoft/view/56643-exam-az-900-topic-1-question-26-discussion/' },
{ 'url': '/discussions/microsoft/view/62797-exam-az-900-topic-1-question-27-discussion/' },
{ 'url': '/discussions/microsoft/view/62807-exam-az-900-topic-1-question-28-discussion/' },
{ 'url': '/discussions/microsoft/view/56650-exam-az-900-topic-1-question-29-discussion/' },
{ 'url': '/discussions/microsoft/view/56651-exam-az-900-topic-1-question-30-discussion/' },
{ 'url': '/discussions/microsoft/view/56915-exam-az-900-topic-1-question-31-discussion/' },
{ 'url': '/discussions/microsoft/view/56358-exam-az-900-topic-1-question-32-discussion/' },
{ 'url': '/discussions/microsoft/view/56317-exam-az-900-topic-1-question-33-discussion/' },
{ 'url': '/discussions/microsoft/view/8931-exam-az-900-topic-1-question-34-discussion/' },
{ 'url': '/discussions/microsoft/view/9153-exam-az-900-topic-1-question-35-discussion/' },
{ 'url': '/discussions/microsoft/view/43997-exam-az-900-topic-1-question-36-discussion/' },
{ 'url': '/discussions/microsoft/view/5731-exam-az-900-topic-1-question-37-discussion/' },
{ 'url': '/discussions/microsoft/view/44356-exam-az-900-topic-1-question-38-discussion/' },
{ 'url': '/discussions/microsoft/view/5733-exam-az-900-topic-1-question-39-discussion/' },
{ 'url': '/discussions/microsoft/view/44357-exam-az-900-topic-1-question-40-discussion/' },
{ 'url': '/discussions/microsoft/view/44358-exam-az-900-topic-1-question-41-discussion/' },
{ 'url': '/discussions/microsoft/view/44823-exam-az-900-topic-1-question-42-discussion/' },
{ 'url': '/discussions/microsoft/view/44053-exam-az-900-topic-1-question-43-discussion/' },
{ 'url': '/discussions/microsoft/view/5737-exam-az-900-topic-1-question-44-discussion/' },
{ 'url': '/discussions/microsoft/view/5062-exam-az-900-topic-1-question-45-discussion/' },
{ 'url': '/discussions/microsoft/view/9155-exam-az-900-topic-1-question-46-discussion/' },
{ 'url': '/discussions/microsoft/view/5738-exam-az-900-topic-1-question-47-discussion/' },
{ 'url': '/discussions/microsoft/view/9147-exam-az-900-topic-1-question-48-discussion/' },
{ 'url': '/discussions/microsoft/view/45659-exam-az-900-topic-1-question-49-discussion/' },
{ 'url': '/discussions/microsoft/view/44018-exam-az-900-topic-1-question-50-discussion/' },
{ 'url': '/discussions/microsoft/view/47158-exam-az-900-topic-1-question-51-discussion/' },
{ 'url': '/discussions/microsoft/view/122824-exam-az-900-topic-1-question-52-discussion/' },
{ 'url': '/discussions/microsoft/view/9591-exam-az-900-topic-1-question-53-discussion/' },
{ 'url': '/discussions/microsoft/view/44535-exam-az-900-topic-1-question-54-discussion/' },
{ 'url': '/discussions/microsoft/view/44148-exam-az-900-topic-1-question-55-discussion/' },
{ 'url': '/discussions/microsoft/view/46420-exam-az-900-topic-1-question-56-discussion/' },
{ 'url': '/discussions/microsoft/view/62811-exam-az-900-topic-1-question-57-discussion/' },
{ 'url': '/discussions/microsoft/view/53855-exam-az-900-topic-1-question-58-discussion/' },
{ 'url': '/discussions/microsoft/view/15451-exam-az-900-topic-1-question-59-discussion/' },
{ 'url': '/discussions/microsoft/view/46487-exam-az-900-topic-1-question-60-discussion/' },
{ 'url': '/discussions/microsoft/view/47470-exam-az-900-topic-1-question-61-discussion/' },
{ 'url': '/discussions/microsoft/view/44411-exam-az-900-topic-1-question-62-discussion/' },
{ 'url': '/discussions/microsoft/view/46760-exam-az-900-topic-1-question-63-discussion/' },
{ 'url': '/discussions/microsoft/view/44583-exam-az-900-topic-1-question-64-discussion/' },
{ 'url': '/discussions/microsoft/view/44339-exam-az-900-topic-1-question-65-discussion/' },
{ 'url': '/discussions/microsoft/view/20442-exam-az-900-topic-1-question-66-discussion/' },
{ 'url': '/discussions/microsoft/view/47673-exam-az-900-topic-1-question-67-discussion/' },
{ 'url': '/discussions/microsoft/view/45120-exam-az-900-topic-1-question-68-discussion/' },
{ 'url': '/discussions/microsoft/view/51582-exam-az-900-topic-1-question-69-discussion/' },
{ 'url': '/discussions/microsoft/view/51428-exam-az-900-topic-1-question-70-discussion/' },
{ 'url': '/discussions/microsoft/view/53847-exam-az-900-topic-1-question-71-discussion/' },
{ 'url': '/discussions/microsoft/view/121213-exam-az-900-topic-1-question-72-discussion/' },
{ 'url': '/discussions/microsoft/view/53938-exam-az-900-topic-1-question-73-discussion/' },
{ 'url': '/discussions/microsoft/view/61114-exam-az-900-topic-1-question-74-discussion/' },
{ 'url': '/discussions/microsoft/view/61176-exam-az-900-topic-1-question-75-discussion/' },
{ 'url': '/discussions/microsoft/view/61344-exam-az-900-topic-1-question-76-discussion/' },
{ 'url': '/discussions/microsoft/view/62998-exam-az-900-topic-1-question-77-discussion/' },
{ 'url': '/discussions/microsoft/view/68980-exam-az-900-topic-1-question-78-discussion/' },
{ 'url': '/discussions/microsoft/view/79523-exam-az-900-topic-1-question-79-discussion/' },
{ 'url': '/discussions/microsoft/view/81510-exam-az-900-topic-1-question-80-discussion/' },
{ 'url': '/discussions/microsoft/view/78358-exam-az-900-topic-1-question-81-discussion/' },
{ 'url': '/discussions/microsoft/view/78398-exam-az-900-topic-1-question-82-discussion/' },
{ 'url': '/discussions/microsoft/view/78464-exam-az-900-topic-1-question-83-discussion/' },
{ 'url': '/discussions/microsoft/view/136651-exam-az-900-topic-1-question-462-discussion/' },
{ 'url': '/discussions/microsoft/view/78624-exam-az-900-topic-1-question-85-discussion/' },
{ 'url': '/discussions/microsoft/view/80048-exam-az-900-topic-1-question-86-discussion/' },
{ 'url': '/discussions/microsoft/view/80244-exam-az-900-topic-1-question-87-discussion/' },
{ 'url': '/discussions/microsoft/view/83342-exam-az-900-topic-1-question-88-discussion/' },
{ 'url': '/discussions/microsoft/view/119727-exam-az-900-topic-1-question-449-discussion/' },
{ 'url': '/discussions/microsoft/view/79401-exam-az-900-topic-1-question-90-discussion/' },
{ 'url': '/discussions/microsoft/view/78399-exam-az-900-topic-1-question-91-discussion/' },
{ 'url': '/discussions/microsoft/view/78787-exam-az-900-topic-1-question-92-discussion/' },
{ 'url': '/discussions/microsoft/view/82618-exam-az-900-topic-1-question-93-discussion/' },
{ 'url': '/discussions/microsoft/view/80769-exam-az-900-topic-1-question-94-discussion/' },
{ 'url': '/discussions/microsoft/view/78779-exam-az-900-topic-1-question-95-discussion/' },
{ 'url': '/discussions/microsoft/view/11601-exam-az-900-topic-1-question-96-discussion/' },
{ 'url': '/discussions/microsoft/view/61122-exam-az-900-topic-1-question-97-discussion/' },
{ 'url': '/discussions/microsoft/view/9953-exam-az-900-topic-1-question-98-discussion/' },
{ 'url': '/discussions/microsoft/view/45536-exam-az-900-topic-1-question-99-discussion/' },
{ 'url': '/discussions/microsoft/view/44003-exam-az-900-topic-1-question-100-discussion/' },
{ 'url': '/discussions/microsoft/view/7698-exam-az-900-topic-1-question-101-discussion/' },
{ 'url': '/discussions/microsoft/view/20073-exam-az-900-topic-1-question-102-discussion/' },
{ 'url': '/discussions/microsoft/view/45977-exam-az-900-topic-1-question-103-discussion/' },
{ 'url': '/discussions/microsoft/view/7785-exam-az-900-topic-1-question-105-discussion/' },
{ 'url': '/discussions/microsoft/view/8446-exam-az-900-topic-1-question-106-discussion/' },
{ 'url': '/discussions/microsoft/view/7995-exam-az-900-topic-1-question-107-discussion/' },
{ 'url': '/discussions/microsoft/view/47314-exam-az-900-topic-1-question-108-discussion/' },
{ 'url': '/discussions/microsoft/view/11144-exam-az-900-topic-1-question-110-discussion/' },
{ 'url': '/discussions/microsoft/view/3205-exam-az-900-topic-1-question-111-discussion/' },
{ 'url': '/discussions/microsoft/view/44752-exam-az-900-topic-1-question-112-discussion/' },
{ 'url': '/discussions/microsoft/view/62833-exam-az-900-topic-1-question-113-discussion/' },
{ 'url': '/discussions/microsoft/view/44761-exam-az-900-topic-1-question-114-discussion/' },
{ 'url': '/discussions/microsoft/view/45069-exam-az-900-topic-1-question-115-discussion/' },
{ 'url': '/discussions/microsoft/view/9652-exam-az-900-topic-1-question-116-discussion/' },
{ 'url': '/discussions/microsoft/view/45324-exam-az-900-topic-1-question-117-discussion/' },
{ 'url': '/discussions/microsoft/view/52366-exam-az-900-topic-1-question-118-discussion/' },
{ 'url': '/discussions/microsoft/view/44436-exam-az-900-topic-1-question-119-discussion/' },
{ 'url': '/discussions/microsoft/view/6408-exam-az-900-topic-1-question-120-discussion/' },
{ 'url': '/discussions/microsoft/view/44258-exam-az-900-topic-1-question-121-discussion/' },
{ 'url': '/discussions/microsoft/view/4466-exam-az-900-topic-1-question-122-discussion/' },
{ 'url': '/discussions/microsoft/view/51304-exam-az-900-topic-1-question-123-discussion/' },
{ 'url': '/discussions/microsoft/view/51489-exam-az-900-topic-1-question-124-discussion/' },
{ 'url': '/discussions/microsoft/view/51886-exam-az-900-topic-1-question-125-discussion/' },
{ 'url': '/discussions/microsoft/view/53294-exam-az-900-topic-1-question-126-discussion/' },
{ 'url': '/discussions/microsoft/view/44033-exam-az-900-topic-1-question-127-discussion/' },
{ 'url': '/discussions/microsoft/view/135162-exam-az-900-topic-1-question-461-discussion/' },
{ 'url': '/discussions/microsoft/view/121427-exam-az-900-topic-1-question-129-discussion/' },
{ 'url': '/discussions/microsoft/view/54067-exam-az-900-topic-1-question-130-discussion/' },
{ 'url': '/discussions/microsoft/view/54052-exam-az-900-topic-1-question-131-discussion/' },
{ 'url': '/discussions/microsoft/view/45560-exam-az-900-topic-1-question-132-discussion/' },
{ 'url': '/discussions/microsoft/view/61255-exam-az-900-topic-1-question-133-discussion/' },
{ 'url': '/discussions/microsoft/view/63081-exam-az-900-topic-1-question-134-discussion/' },
{ 'url': '/discussions/microsoft/view/69096-exam-az-900-topic-1-question-135-discussion/' },
{ 'url': '/discussions/microsoft/view/69775-exam-az-900-topic-1-question-136-discussion/' },
{ 'url': '/discussions/microsoft/view/68715-exam-az-900-topic-1-question-137-discussion/' },
{ 'url': '/discussions/microsoft/view/79913-exam-az-900-topic-1-question-138-discussion/' },
{ 'url': '/discussions/microsoft/view/79690-exam-az-900-topic-1-question-140-discussion/' },
{ 'url': '/discussions/microsoft/view/79915-exam-az-900-topic-1-question-141-discussion/' },
{ 'url': '/discussions/microsoft/view/80311-exam-az-900-topic-1-question-142-discussion/' },
{ 'url': '/discussions/microsoft/view/82429-exam-az-900-topic-1-question-143-discussion/' },
{ 'url': '/discussions/microsoft/view/79916-exam-az-900-topic-1-question-144-discussion/' },
{ 'url': '/discussions/microsoft/view/52910-exam-az-900-topic-1-question-145-discussion/' },
{ 'url': '/discussions/microsoft/view/84410-exam-az-900-topic-1-question-146-discussion/' },
{ 'url': '/discussions/microsoft/view/83522-exam-az-900-topic-1-question-147-discussion/' },
{ 'url': '/discussions/microsoft/view/84412-exam-az-900-topic-1-question-148-discussion/' },
{ 'url': '/discussions/microsoft/view/82794-exam-az-900-topic-1-question-149-discussion/' },
{ 'url': '/discussions/microsoft/view/80708-exam-az-900-topic-1-question-150-discussion/' },
{ 'url': '/discussions/microsoft/view/81560-exam-az-900-topic-1-question-151-discussion/' },
{ 'url': '/discussions/microsoft/view/44259-exam-az-900-topic-1-question-152-discussion/' },
{ 'url': '/discussions/microsoft/view/9194-exam-az-900-topic-1-question-153-discussion/' },
{ 'url': '/discussions/microsoft/view/11135-exam-az-900-topic-1-question-154-discussion/' },
{ 'url': '/discussions/microsoft/view/4948-exam-az-900-topic-1-question-155-discussion/' },
{ 'url': '/discussions/microsoft/view/83758-exam-az-900-topic-1-question-156-discussion/' },
{ 'url': '/discussions/microsoft/view/78635-exam-az-900-topic-1-question-157-discussion/' },
{ 'url': '/discussions/microsoft/view/84026-exam-az-900-topic-1-question-158-discussion/' },
{ 'url': '/discussions/microsoft/view/10023-exam-az-900-topic-1-question-159-discussion/' },
{ 'url': '/discussions/microsoft/view/10808-exam-az-900-topic-1-question-160-discussion/' },
{ 'url': '/discussions/microsoft/view/12156-exam-az-900-topic-1-question-161-discussion/' },
{ 'url': '/discussions/microsoft/view/84024-exam-az-900-topic-1-question-162-discussion/' },
{ 'url': '/discussions/microsoft/view/84471-exam-az-900-topic-1-question-163-discussion/' },
{ 'url': '/discussions/microsoft/view/3203-exam-az-900-topic-1-question-164-discussion/' },
{ 'url': '/discussions/microsoft/view/2971-exam-az-900-topic-1-question-165-discussion/' },
{ 'url': '/discussions/microsoft/view/45182-exam-az-900-topic-1-question-166-discussion/' },
{ 'url': '/discussions/microsoft/view/12298-exam-az-900-topic-1-question-167-discussion/' },
{ 'url': '/discussions/microsoft/view/44024-exam-az-900-topic-1-question-168-discussion/' },
{ 'url': '/discussions/microsoft/view/44734-exam-az-900-topic-1-question-169-discussion/' },
{ 'url': '/discussions/microsoft/view/44741-exam-az-900-topic-1-question-170-discussion/' },
{ 'url': '/discussions/microsoft/view/11191-exam-az-900-topic-1-question-171-discussion/' },
{ 'url': '/discussions/microsoft/view/44742-exam-az-900-topic-1-question-172-discussion/' },
{ 'url': '/discussions/microsoft/view/9991-exam-az-900-topic-1-question-173-discussion/' },
{ 'url': '/discussions/microsoft/view/12323-exam-az-900-topic-1-question-174-discussion/' },
{ 'url': '/discussions/microsoft/view/8995-exam-az-900-topic-1-question-175-discussion/' },
{ 'url': '/discussions/microsoft/view/5647-exam-az-900-topic-1-question-176-discussion/' },
{ 'url': '/discussions/microsoft/view/11131-exam-az-900-topic-1-question-177-discussion/' },
{ 'url': '/discussions/microsoft/view/9301-exam-az-900-topic-1-question-178-discussion/' },
{ 'url': '/discussions/microsoft/view/48007-exam-az-900-topic-1-question-179-discussion/' },
{ 'url': '/discussions/microsoft/view/46384-exam-az-900-topic-1-question-180-discussion/' },
{ 'url': '/discussions/microsoft/view/47125-exam-az-900-topic-1-question-181-discussion/' },
{ 'url': '/discussions/microsoft/view/69479-exam-az-900-topic-1-question-182-discussion/' },
{ 'url': '/discussions/microsoft/view/8755-exam-az-900-topic-1-question-183-discussion/' },
{ 'url': '/discussions/microsoft/view/9162-exam-az-900-topic-1-question-184-discussion/' },
{ 'url': '/discussions/microsoft/view/44038-exam-az-900-topic-1-question-185-discussion/' },
{ 'url': '/discussions/microsoft/view/44185-exam-az-900-topic-1-question-186-discussion/' },
{ 'url': '/discussions/microsoft/view/9632-exam-az-900-topic-1-question-187-discussion/' },
{ 'url': '/discussions/microsoft/view/51502-exam-az-900-topic-1-question-188-discussion/' },
{ 'url': '/discussions/microsoft/view/45073-exam-az-900-topic-1-question-189-discussion/' },
{ 'url': '/discussions/microsoft/view/45074-exam-az-900-topic-1-question-190-discussion/' },
{ 'url': '/discussions/microsoft/view/44117-exam-az-900-topic-1-question-191-discussion/' },
{ 'url': '/discussions/microsoft/view/45075-exam-az-900-topic-1-question-192-discussion/' },
{ 'url': '/discussions/microsoft/view/51980-exam-az-900-topic-1-question-193-discussion/' },
{ 'url': '/discussions/microsoft/view/53894-exam-az-900-topic-1-question-194-discussion/' },
{ 'url': '/discussions/microsoft/view/45076-exam-az-900-topic-1-question-195-discussion/' },
{ 'url': '/discussions/microsoft/view/9649-exam-az-900-topic-1-question-196-discussion/' },
{ 'url': '/discussions/microsoft/view/63075-exam-az-900-topic-1-question-197-discussion/' },
{ 'url': '/discussions/microsoft/view/69583-exam-az-900-topic-1-question-198-discussion/' },
{ 'url': '/discussions/microsoft/view/80968-exam-az-900-topic-1-question-199-discussion/' },
{ 'url': '/discussions/microsoft/view/138800-exam-az-900-topic-1-question-459-discussion/' },
{ 'url': '/discussions/microsoft/view/84319-exam-az-900-topic-1-question-201-discussion/' },
{ 'url': '/discussions/microsoft/view/14896-exam-az-900-topic-1-question-202-discussion/' },
{ 'url': '/discussions/microsoft/view/8413-exam-az-900-topic-1-question-203-discussion/' },
{ 'url': '/discussions/microsoft/view/69026-exam-az-900-topic-1-question-204-discussion/' },
{ 'url': '/discussions/microsoft/view/44512-exam-az-900-topic-1-question-206-discussion/' },
{ 'url': '/discussions/microsoft/view/45180-exam-az-900-topic-1-question-207-discussion/' },
{ 'url': '/discussions/microsoft/view/44320-exam-az-900-topic-1-question-208-discussion/' },
{ 'url': '/discussions/microsoft/view/80696-exam-az-900-topic-1-question-209-discussion/' },
{ 'url': '/discussions/microsoft/view/85190-exam-az-900-topic-1-question-210-discussion/' },
{ 'url': '/discussions/microsoft/view/85345-exam-az-900-topic-1-question-211-discussion/' },
{ 'url': '/discussions/microsoft/view/61501-exam-az-900-topic-1-question-212-discussion/' },
{ 'url': '/discussions/microsoft/view/44130-exam-az-900-topic-1-question-213-discussion/' },
{ 'url': '/discussions/microsoft/view/20007-exam-az-900-topic-1-question-214-discussion/' },
{ 'url': '/discussions/microsoft/view/13347-exam-az-900-topic-1-question-215-discussion/' },
{ 'url': '/discussions/microsoft/view/11903-exam-az-900-topic-1-question-216-discussion/' },
{ 'url': '/discussions/microsoft/view/11176-exam-az-900-topic-1-question-217-discussion/' },
{ 'url': '/discussions/microsoft/view/11128-exam-az-900-topic-1-question-218-discussion/' },
{ 'url': '/discussions/microsoft/view/45187-exam-az-900-topic-1-question-219-discussion/' },
{ 'url': '/discussions/microsoft/view/20514-exam-az-900-topic-1-question-220-discussion/' },
{ 'url': '/discussions/microsoft/view/10539-exam-az-900-topic-1-question-221-discussion/' },
{ 'url': '/discussions/microsoft/view/53876-exam-az-900-topic-1-question-222-discussion/' },
{ 'url': '/discussions/microsoft/view/61089-exam-az-900-topic-1-question-223-discussion/' },
{ 'url': '/discussions/microsoft/view/61091-exam-az-900-topic-1-question-224-discussion/' },
{ 'url': '/discussions/microsoft/view/44088-exam-az-900-topic-1-question-225-discussion/' },
{ 'url': '/discussions/microsoft/view/45974-exam-az-900-topic-1-question-226-discussion/' },
{ 'url': '/discussions/microsoft/view/62848-exam-az-900-topic-1-question-227-discussion/' },
{ 'url': '/discussions/microsoft/view/63192-exam-az-900-topic-1-question-228-discussion/' },
{ 'url': '/discussions/microsoft/view/63451-exam-az-900-topic-1-question-229-discussion/' },
{ 'url': '/discussions/microsoft/view/63363-exam-az-900-topic-1-question-230-discussion/' },
{ 'url': '/discussions/microsoft/view/63117-exam-az-900-topic-1-question-231-discussion/' },
{ 'url': '/discussions/microsoft/view/62789-exam-az-900-topic-1-question-232-discussion/' },
{ 'url': '/discussions/microsoft/view/69117-exam-az-900-topic-1-question-233-discussion/' },
{ 'url': '/discussions/microsoft/view/84453-exam-az-900-topic-1-question-234-discussion/' },
{ 'url': '/discussions/microsoft/view/85454-exam-az-900-topic-1-question-235-discussion/' },
{ 'url': '/discussions/microsoft/view/85455-exam-az-900-topic-1-question-236-discussion/' },
{ 'url': '/discussions/microsoft/view/85576-exam-az-900-topic-1-question-237-discussion/' },
{ 'url': '/discussions/microsoft/view/79706-exam-az-900-topic-1-question-238-discussion/' },
{ 'url': '/discussions/microsoft/view/85456-exam-az-900-topic-1-question-239-discussion/' },
{ 'url': '/discussions/microsoft/view/87279-exam-az-900-topic-1-question-240-discussion/' },
{ 'url': '/discussions/microsoft/view/85476-exam-az-900-topic-1-question-241-discussion/' },
{ 'url': '/discussions/microsoft/view/85480-exam-az-900-topic-1-question-242-discussion/' },
{ 'url': '/discussions/microsoft/view/79333-exam-az-900-topic-1-question-243-discussion/' },
{ 'url': '/discussions/microsoft/view/85481-exam-az-900-topic-1-question-244-discussion/' },
{ 'url': '/discussions/microsoft/view/85482-exam-az-900-topic-1-question-245-discussion/' },
{ 'url': '/discussions/microsoft/view/78492-exam-az-900-topic-1-question-246-discussion/' },
{ 'url': '/discussions/microsoft/view/87281-exam-az-900-topic-1-question-247-discussion/' },
{ 'url': '/discussions/microsoft/view/8049-exam-az-900-topic-1-question-248-discussion/' },
{ 'url': '/discussions/microsoft/view/11141-exam-az-900-topic-1-question-249-discussion/' },
{ 'url': '/discussions/microsoft/view/38449-exam-az-900-topic-1-question-250-discussion/' },
{ 'url': '/discussions/microsoft/view/46031-exam-az-900-topic-1-question-251-discussion/' },
{ 'url': '/discussions/microsoft/view/46597-exam-az-900-topic-1-question-252-discussion/' },
{ 'url': '/discussions/microsoft/view/8437-exam-az-900-topic-1-question-253-discussion/' },
{ 'url': '/discussions/microsoft/view/9018-exam-az-900-topic-1-question-254-discussion/' },
{ 'url': '/discussions/microsoft/view/10423-exam-az-900-topic-1-question-255-discussion/' },
{ 'url': '/discussions/microsoft/view/11867-exam-az-900-topic-1-question-256-discussion/' },
{ 'url': '/discussions/microsoft/view/45183-exam-az-900-topic-1-question-257-discussion/' },
{ 'url': '/discussions/microsoft/view/52250-exam-az-900-topic-1-question-258-discussion/' },
{ 'url': '/discussions/microsoft/view/44015-exam-az-900-topic-1-question-259-discussion/' },
{ 'url': '/discussions/microsoft/view/7310-exam-az-900-topic-1-question-260-discussion/' },
{ 'url': '/discussions/microsoft/view/51524-exam-az-900-topic-1-question-261-discussion/' },
{ 'url': '/discussions/microsoft/view/7793-exam-az-900-topic-1-question-262-discussion/' },
{ 'url': '/discussions/microsoft/view/10647-exam-az-900-topic-1-question-263-discussion/' },
{ 'url': '/discussions/microsoft/view/45184-exam-az-900-topic-1-question-264-discussion/' },
{ 'url': '/discussions/microsoft/view/51322-exam-az-900-topic-1-question-265-discussion/' },
{ 'url': '/discussions/microsoft/view/137532-exam-az-900-topic-1-question-458-discussion/' },
{ 'url': '/discussions/microsoft/view/44371-exam-az-900-topic-1-question-267-discussion/' },
{ 'url': '/discussions/microsoft/view/45185-exam-az-900-topic-1-question-268-discussion/' },
{ 'url': '/discussions/microsoft/view/5555-exam-az-900-topic-1-question-269-discussion/' },
{ 'url': '/discussions/microsoft/view/45020-exam-az-900-topic-1-question-270-discussion/' },
{ 'url': '/discussions/microsoft/view/10819-exam-az-900-topic-1-question-271-discussion/' },
{ 'url': '/discussions/microsoft/view/45186-exam-az-900-topic-1-question-272-discussion/' },
{ 'url': '/discussions/microsoft/view/2991-exam-az-900-topic-1-question-273-discussion/' },
{ 'url': '/discussions/microsoft/view/8445-exam-az-900-topic-1-question-274-discussion/' },
{ 'url': '/discussions/microsoft/view/44527-exam-az-900-topic-1-question-275-discussion/' },
{ 'url': '/discussions/microsoft/view/70938-exam-az-900-topic-1-question-276-discussion/' },
{ 'url': '/discussions/microsoft/view/47447-exam-az-900-topic-1-question-277-discussion/' },
{ 'url': '/discussions/microsoft/view/61336-exam-az-900-topic-1-question-278-discussion/' },
{ 'url': '/discussions/microsoft/view/11129-exam-az-900-topic-1-question-279-discussion/' },
{ 'url': '/discussions/microsoft/view/44791-exam-az-900-topic-1-question-280-discussion/' },
{ 'url': '/discussions/microsoft/view/61611-exam-az-900-topic-1-question-281-discussion/' },
{ 'url': '/discussions/microsoft/view/63588-exam-az-900-topic-1-question-282-discussion/' },
{ 'url': '/discussions/microsoft/view/63119-exam-az-900-topic-1-question-283-discussion/' },
{ 'url': '/discussions/microsoft/view/45722-exam-az-900-topic-1-question-284-discussion/' },
{ 'url': '/discussions/microsoft/view/68711-exam-az-900-topic-1-question-285-discussion/' },
{ 'url': '/discussions/microsoft/view/70154-exam-az-900-topic-1-question-286-discussion/' },
{ 'url': '/discussions/microsoft/view/69018-exam-az-900-topic-1-question-287-discussion/' },
{ 'url': '/discussions/microsoft/view/85937-exam-az-900-topic-1-question-288-discussion/' },
{ 'url': '/discussions/microsoft/view/68753-exam-az-900-topic-1-question-289-discussion/' },
{ 'url': '/discussions/microsoft/view/85768-exam-az-900-topic-1-question-290-discussion/' },
{ 'url': '/discussions/microsoft/view/81731-exam-az-900-topic-1-question-291-discussion/' },
{ 'url': '/discussions/microsoft/view/78619-exam-az-900-topic-1-question-292-discussion/' },
{ 'url': '/discussions/microsoft/view/63318-exam-az-900-topic-1-question-293-discussion/' },
{ 'url': '/discussions/microsoft/view/20450-exam-az-900-topic-1-question-294-discussion/' },
{ 'url': '/discussions/microsoft/view/44454-exam-az-900-topic-1-question-295-discussion/' },
{ 'url': '/discussions/microsoft/view/61128-exam-az-900-topic-1-question-296-discussion/' },
{ 'url': '/discussions/microsoft/view/45819-exam-az-900-topic-1-question-297-discussion/' },
{ 'url': '/discussions/microsoft/view/54070-exam-az-900-topic-1-question-298-discussion/' },
{ 'url': '/discussions/microsoft/view/46624-exam-az-900-topic-1-question-299-discussion/' },
{ 'url': '/discussions/microsoft/view/48043-exam-az-900-topic-1-question-300-discussion/' },
{ 'url': '/discussions/microsoft/view/46512-exam-az-900-topic-1-question-301-discussion/' },
{ 'url': '/discussions/microsoft/view/47561-exam-az-900-topic-1-question-302-discussion/' },
{ 'url': '/discussions/microsoft/view/44197-exam-az-900-topic-1-question-303-discussion/' },
{ 'url': '/discussions/microsoft/view/9327-exam-az-900-topic-1-question-305-discussion/' },
{ 'url': '/discussions/microsoft/view/52549-exam-az-900-topic-1-question-306-discussion/' },
{ 'url': '/discussions/microsoft/view/90758-exam-az-900-topic-1-question-307-discussion/' },
{ 'url': '/discussions/microsoft/view/84570-exam-az-900-topic-1-question-308-discussion/' },
{ 'url': '/discussions/microsoft/view/44788-exam-az-900-topic-1-question-309-discussion/' },
{ 'url': '/discussions/microsoft/view/87589-exam-az-900-topic-1-question-310-discussion/' },
{ 'url': '/discussions/microsoft/view/45865-exam-az-900-topic-1-question-311-discussion/' },
{ 'url': '/discussions/microsoft/view/48486-exam-az-900-topic-1-question-312-discussion/' },
{ 'url': '/discussions/microsoft/view/45710-exam-az-900-topic-1-question-313-discussion/' },
{ 'url': '/discussions/microsoft/view/5741-exam-az-900-topic-1-question-314-discussion/' },
{ 'url': '/discussions/microsoft/view/14790-exam-az-900-topic-1-question-315-discussion/' },
{ 'url': '/discussions/microsoft/view/5027-exam-az-900-topic-1-question-316-discussion/' },
{ 'url': '/discussions/microsoft/view/44187-exam-az-900-topic-1-question-317-discussion/' },
{ 'url': '/discussions/microsoft/view/9057-exam-az-900-topic-1-question-318-discussion/' },
{ 'url': '/discussions/microsoft/view/52065-exam-az-900-topic-1-question-319-discussion/' },
{ 'url': '/discussions/microsoft/view/13288-exam-az-900-topic-1-question-320-discussion/' },
{ 'url': '/discussions/microsoft/view/45709-exam-az-900-topic-1-question-321-discussion/' },
{ 'url': '/discussions/microsoft/view/17697-exam-az-900-topic-1-question-322-discussion/' },
{ 'url': '/discussions/microsoft/view/51291-exam-az-900-topic-1-question-323-discussion/' },
{ 'url': '/discussions/microsoft/view/51191-exam-az-900-topic-1-question-324-discussion/' },
{ 'url': '/discussions/microsoft/view/53883-exam-az-900-topic-1-question-325-discussion/' },
{ 'url': '/discussions/microsoft/view/7152-exam-az-900-topic-1-question-326-discussion/' },
{ 'url': '/discussions/microsoft/view/44002-exam-az-900-topic-1-question-328-discussion/' },
{ 'url': '/discussions/microsoft/view/54072-exam-az-900-topic-1-question-329-discussion/' },
{ 'url': '/discussions/microsoft/view/45912-exam-az-900-topic-1-question-330-discussion/' },
{ 'url': '/discussions/microsoft/view/45280-exam-az-900-topic-1-question-331-discussion/' },
{ 'url': '/discussions/microsoft/view/61053-exam-az-900-topic-1-question-332-discussion/' },
{ 'url': '/discussions/microsoft/view/9610-exam-az-900-topic-1-question-334-discussion/' },
{ 'url': '/discussions/microsoft/view/44825-exam-az-900-topic-1-question-335-discussion/' },
{ 'url': '/discussions/microsoft/view/45629-exam-az-900-topic-1-question-336-discussion/' },
{ 'url': '/discussions/microsoft/view/63383-exam-az-900-topic-1-question-337-discussion/' },
{ 'url': '/discussions/microsoft/view/46102-exam-az-900-topic-1-question-338-discussion/' },
{ 'url': '/discussions/microsoft/view/33447-exam-az-900-topic-1-question-339-discussion/' },
{ 'url': '/discussions/microsoft/view/44082-exam-az-900-topic-1-question-340-discussion/' },
{ 'url': '/discussions/microsoft/view/70105-exam-az-900-topic-1-question-341-discussion/' },
{ 'url': '/discussions/microsoft/view/81146-exam-az-900-topic-1-question-342-discussion/' },
{ 'url': '/discussions/microsoft/view/78712-exam-az-900-topic-1-question-343-discussion/' },
{ 'url': '/discussions/microsoft/view/86098-exam-az-900-topic-1-question-344-discussion/' },
{ 'url': '/discussions/microsoft/view/82496-exam-az-900-topic-1-question-345-discussion/' },
{ 'url': '/discussions/microsoft/view/85320-exam-az-900-topic-1-question-346-discussion/' },
{ 'url': '/discussions/microsoft/view/80139-exam-az-900-topic-1-question-347-discussion/' },
{ 'url': '/discussions/microsoft/view/134997-exam-az-900-topic-1-question-457-discussion/' },
{ 'url': '/discussions/microsoft/view/86119-exam-az-900-topic-1-question-350-discussion/' },
{ 'url': '/discussions/microsoft/view/81476-exam-az-900-topic-1-question-351-discussion/' },
{ 'url': '/discussions/microsoft/view/92756-exam-az-900-topic-1-question-352-discussion/' },
{ 'url': '/discussions/microsoft/view/81478-exam-az-900-topic-1-question-353-discussion/' },
{ 'url': '/discussions/microsoft/view/85344-exam-az-900-topic-1-question-355-discussion/' },
{ 'url': '/discussions/microsoft/view/7886-exam-az-900-topic-1-question-356-discussion/' },
{ 'url': '/discussions/microsoft/view/11535-exam-az-900-topic-1-question-357-discussion/' },
{ 'url': '/discussions/microsoft/view/10463-exam-az-900-topic-1-question-358-discussion/' },
{ 'url': '/discussions/microsoft/view/10554-exam-az-900-topic-1-question-359-discussion/' },
{ 'url': '/discussions/microsoft/view/44304-exam-az-900-topic-1-question-360-discussion/' },
{ 'url': '/discussions/microsoft/view/54071-exam-az-900-topic-1-question-361-discussion/' },
{ 'url': '/discussions/microsoft/view/9262-exam-az-900-topic-1-question-362-discussion/' },
{ 'url': '/discussions/microsoft/view/54656-exam-az-900-topic-1-question-363-discussion/' },
{ 'url': '/discussions/microsoft/view/9607-exam-az-900-topic-1-question-364-discussion/' },
{ 'url': '/discussions/microsoft/view/7151-exam-az-900-topic-1-question-365-discussion/' },
{ 'url': '/discussions/microsoft/view/4803-exam-az-900-topic-1-question-366-discussion/' },
{ 'url': '/discussions/microsoft/view/11145-exam-az-900-topic-1-question-367-discussion/' },
{ 'url': '/discussions/microsoft/view/9809-exam-az-900-topic-1-question-368-discussion/' },
{ 'url': '/discussions/microsoft/view/13602-exam-az-900-topic-1-question-369-discussion/' },
{ 'url': '/discussions/microsoft/view/17297-exam-az-900-topic-1-question-370-discussion/' },
{ 'url': '/discussions/microsoft/view/29856-exam-az-900-topic-1-question-371-discussion/' },
{ 'url': '/discussions/microsoft/view/135699-exam-az-900-topic-1-question-455-discussion/' },
{ 'url': '/discussions/microsoft/view/78724-exam-az-900-topic-1-question-374-discussion/' },
{ 'url': '/discussions/microsoft/view/86636-exam-az-900-topic-1-question-375-discussion/' },
{ 'url': '/discussions/microsoft/view/85491-exam-az-900-topic-1-question-376-discussion/' },
{ 'url': '/discussions/microsoft/view/78880-exam-az-900-topic-1-question-377-discussion/' },
{ 'url': '/discussions/microsoft/view/82216-exam-az-900-topic-1-question-378-discussion/' },
{ 'url': '/discussions/microsoft/view/78501-exam-az-900-topic-1-question-379-discussion/' },
{ 'url': '/discussions/microsoft/view/81954-exam-az-900-topic-1-question-380-discussion/' },
{ 'url': '/discussions/microsoft/view/79306-exam-az-900-topic-1-question-381-discussion/' },
{ 'url': '/discussions/microsoft/view/79307-exam-az-900-topic-1-question-382-discussion/' },
{ 'url': '/discussions/microsoft/view/78506-exam-az-900-topic-1-question-383-discussion/' },
{ 'url': '/discussions/microsoft/view/84576-exam-az-900-topic-1-question-384-discussion/' },
{ 'url': '/discussions/microsoft/view/85328-exam-az-900-topic-1-question-385-discussion/' },
{ 'url': '/discussions/microsoft/view/93738-exam-az-900-topic-1-question-386-discussion/' },
{ 'url': '/discussions/microsoft/view/94667-exam-az-900-topic-1-question-387-discussion/' },
{ 'url': '/discussions/microsoft/view/94433-exam-az-900-topic-1-question-388-discussion/' },
{ 'url': '/discussions/microsoft/view/93462-exam-az-900-topic-1-question-389-discussion/' },
{ 'url': '/discussions/microsoft/view/119859-exam-az-900-topic-1-question-447-discussion/' },
{ 'url': '/discussions/microsoft/view/93152-exam-az-900-topic-1-question-391-discussion/' },
{ 'url': '/discussions/microsoft/view/94394-exam-az-900-topic-1-question-392-discussion/' },
{ 'url': '/discussions/microsoft/view/94438-exam-az-900-topic-1-question-393-discussion/' },
{ 'url': '/discussions/microsoft/view/93154-exam-az-900-topic-1-question-394-discussion/' },
{ 'url': '/discussions/microsoft/view/93305-exam-az-900-topic-1-question-395-discussion/' },
{ 'url': '/discussions/microsoft/view/94658-exam-az-900-topic-1-question-396-discussion/' },
{ 'url': '/discussions/microsoft/view/93318-exam-az-900-topic-1-question-397-discussion/' },
{ 'url': '/discussions/microsoft/view/95495-exam-az-900-topic-1-question-398-discussion/' },
{ 'url': '/discussions/microsoft/view/95351-exam-az-900-topic-1-question-399-discussion/' },
{ 'url': '/discussions/microsoft/view/94663-exam-az-900-topic-1-question-400-discussion/' },
{ 'url': '/discussions/microsoft/view/93155-exam-az-900-topic-1-question-401-discussion/' },
{ 'url': '/discussions/microsoft/view/93747-exam-az-900-topic-1-question-402-discussion/' },
{ 'url': '/discussions/microsoft/view/93244-exam-az-900-topic-1-question-403-discussion/' },
{ 'url': '/discussions/microsoft/view/93464-exam-az-900-topic-1-question-404-discussion/' },
{ 'url': '/discussions/microsoft/view/93749-exam-az-900-topic-1-question-405-discussion/' },
{ 'url': '/discussions/microsoft/view/94324-exam-az-900-topic-1-question-406-discussion/' },
{ 'url': '/discussions/microsoft/view/93210-exam-az-900-topic-1-question-407-discussion/' },
{ 'url': '/discussions/microsoft/view/125593-exam-az-900-topic-1-question-408-discussion/' },
{ 'url': '/discussions/microsoft/view/135698-exam-az-900-topic-1-question-454-discussion/' },
{ 'url': '/discussions/microsoft/view/131690-exam-az-900-topic-1-question-410-discussion/' },
{ 'url': '/discussions/microsoft/view/93153-exam-az-900-topic-1-question-411-discussion/' },
{ 'url': '/discussions/microsoft/view/93159-exam-az-900-topic-1-question-412-discussion/' },
{ 'url': '/discussions/microsoft/view/108697-exam-az-900-topic-1-question-413-discussion/' },
{ 'url': '/discussions/microsoft/view/110430-exam-az-900-topic-1-question-414-discussion/' },
{ 'url': '/discussions/microsoft/view/109460-exam-az-900-topic-1-question-415-discussion/' },
{ 'url': '/discussions/microsoft/view/109416-exam-az-900-topic-1-question-416-discussion/' },
{ 'url': '/discussions/microsoft/view/131691-exam-az-900-topic-1-question-417-discussion/' },
{ 'url': '/discussions/microsoft/view/108910-exam-az-900-topic-1-question-418-discussion/' },
{ 'url': '/discussions/microsoft/view/112281-exam-az-900-topic-1-question-419-discussion/' },
{ 'url': '/discussions/microsoft/view/108911-exam-az-900-topic-1-question-420-discussion/' },
{ 'url': '/discussions/microsoft/view/112063-exam-az-900-topic-1-question-421-discussion/' },
{ 'url': '/discussions/microsoft/view/110614-exam-az-900-topic-1-question-422-discussion/' },
{ 'url': '/discussions/microsoft/view/111575-exam-az-900-topic-1-question-423-discussion/' },
{ 'url': '/discussions/microsoft/view/113379-exam-az-900-topic-1-question-424-discussion/' },
{ 'url': '/discussions/microsoft/view/113380-exam-az-900-topic-1-question-425-discussion/' },
{ 'url': '/discussions/microsoft/view/113381-exam-az-900-topic-1-question-426-discussion/' },
{ 'url': '/discussions/microsoft/view/113383-exam-az-900-topic-1-question-427-discussion/' },
{ 'url': '/discussions/microsoft/view/112285-exam-az-900-topic-1-question-428-discussion/' },
{ 'url': '/discussions/microsoft/view/111576-exam-az-900-topic-1-question-429-discussion/' },
{ 'url': '/discussions/microsoft/view/112286-exam-az-900-topic-1-question-430-discussion/' },
{ 'url': '/discussions/microsoft/view/112287-exam-az-900-topic-1-question-431-discussion/' },
{ 'url': '/discussions/microsoft/view/112288-exam-az-900-topic-1-question-432-discussion/' },
{ 'url': '/discussions/microsoft/view/113385-exam-az-900-topic-1-question-433-discussion/' },
{ 'url': '/discussions/microsoft/view/113386-exam-az-900-topic-1-question-434-discussion/' },
{ 'url': '/discussions/microsoft/view/112467-exam-az-900-topic-1-question-435-discussion/' },
{ 'url': '/discussions/microsoft/view/116458-exam-az-900-topic-1-question-436-discussion/' },
{ 'url': '/discussions/microsoft/view/131701-exam-az-900-topic-1-question-437-discussion/' },
{ 'url': '/discussions/microsoft/view/121275-exam-az-900-topic-1-question-438-discussion/' },
{ 'url': '/discussions/microsoft/view/119594-exam-az-900-topic-1-question-439-discussion/' },
{ 'url': '/discussions/microsoft/view/134996-exam-az-900-topic-1-question-453-discussion/' },
{ 'url': '/discussions/microsoft/view/131641-exam-az-900-topic-1-question-452-discussion/' },
{ 'url': '/discussions/microsoft/view/119697-exam-az-900-topic-1-question-443-discussion/' },
{ 'url': '/discussions/microsoft/view/119596-exam-az-900-topic-1-question-444-discussion/' },
{ 'url': '/discussions/microsoft/view/121364-exam-az-900-topic-1-question-445-discussion/' },
{ 'url': '/discussions/microsoft/view/131933-exam-az-900-topic-1-question-446-discussion/' },
{ 'url': '/discussions/microsoft/view/130348-exam-az-900-topic-1-question-447-discussion/' },
{ 'url': '/discussions/microsoft/view/131413-exam-az-900-topic-1-question-448-discussion/' },
{ 'url': '/discussions/microsoft/view/132659-exam-az-900-topic-1-question-449-discussion/' },
{ 'url': '/discussions/microsoft/view/133605-exam-az-900-topic-1-question-450-discussion/' },
{ 'url': '/discussions/microsoft/view/133606-exam-az-900-topic-1-question-451-discussion/' },
{ 'url': '/discussions/microsoft/view/148447-exam-az-900-topic-1-question-452-discussion/' },
{ 'url': '/discussions/microsoft/view/150075-exam-az-900-topic-1-question-453-discussion/' },
{ 'url': '/discussions/microsoft/view/148448-exam-az-900-topic-1-question-454-discussion/' },
{ 'url': '/discussions/microsoft/view/149722-exam-az-900-topic-1-question-455-discussion/' },
{ 'url': '/discussions/microsoft/view/138496-exam-az-900-topic-1-question-456-discussion/' },
{ 'url': '/discussions/microsoft/view/150418-exam-az-900-topic-1-question-457-discussion/' },
{ 'url': '/discussions/microsoft/view/148766-exam-az-900-topic-1-question-458-discussion/' },
{ 'url': '/discussions/microsoft/view/150398-exam-az-900-topic-1-question-459-discussion/' },
{ 'url': '/discussions/microsoft/view/136231-exam-az-900-topic-1-question-460-discussion/' },
{ 'url': '/discussions/microsoft/view/150399-exam-az-900-topic-1-question-461-discussion/' },
{ 'url': '/discussions/microsoft/view/150258-exam-az-900-topic-1-question-462-discussion/' },
{ 'url': '/discussions/microsoft/view/150502-exam-az-900-topic-1-question-463-discussion/' },
{ 'url': '/discussions/microsoft/view/148926-exam-az-900-topic-1-question-464-discussion/' },
{ 'url': '/discussions/microsoft/view/150726-exam-az-900-topic-1-question-465-discussion/' },
{ 'url': '/discussions/microsoft/view/150834-exam-az-900-topic-1-question-467-discussion/' },
{ 'url': '/discussions/microsoft/view/150835-exam-az-900-topic-1-question-468-discussion/' },
{ 'url': '/discussions/microsoft/view/151024-exam-az-900-topic-1-question-469-discussion/' },
{ 'url': '/discussions/microsoft/view/150836-exam-az-900-topic-1-question-470-discussion/' },
{ 'url': '/discussions/microsoft/view/151025-exam-az-900-topic-1-question-471-discussion/' },
{ 'url': '/discussions/microsoft/view/151344-exam-az-900-topic-1-question-472-discussion/' },
{ 'url': '/discussions/microsoft/view/151778-exam-az-900-topic-1-question-474-discussion/' },
]

driver = set_chrome_driver()

for i in range(len(urls)):
   #print(urls[i]['url'])
   open_exam(driver, urls[i]['url'])

driver.quit()

url=/discussions/microsoft/view/62815-exam-az-900-topic-1-question-1-discussion/, data_id = 805024
url=/discussions/microsoft/view/56934-exam-az-900-topic-1-question-2-discussion/, data_id = 805025
url=/discussions/microsoft/view/56418-exam-az-900-topic-1-question-3-discussion/, data_id = 805026
url=/discussions/microsoft/view/56881-exam-az-900-topic-1-question-4-discussion/, data_id = 805027
url=/discussions/microsoft/view/56882-exam-az-900-topic-1-question-5-discussion/, data_id = 805028
url=/discussions/microsoft/view/56559-exam-az-900-topic-1-question-6-discussion/, data_id = 805029
url=/discussions/microsoft/view/56422-exam-az-900-topic-1-question-7-discussion/, data_id = 805030
url=/discussions/microsoft/view/56761-exam-az-900-topic-1-question-8-discussion/, data_id = 805031
url=/discussions/microsoft/view/62985-exam-az-900-topic-1-question-9-discussion/, data_id = 805032
url=/discussions/microsoft/view/56453-exam-az-900-topic-1-question-10-discussion/, data_id = 805033
url=/discussions/microsoft/view/56624-exam-az-900-topic-1-question-11-discussion/, data_id = 805034
url=/discussions/microsoft/view/56625-exam-az-900-topic-1-question-12-discussion/, data_id = 805035
url=/discussions/microsoft/view/56627-exam-az-900-topic-1-question-13-discussion/, data_id = 805036
url=/discussions/microsoft/view/56918-exam-az-900-topic-1-question-14-discussion/, data_id = 805037
url=/discussions/microsoft/view/56888-exam-az-900-topic-1-question-15-discussion/, data_id = 805038
url=/discussions/microsoft/view/56892-exam-az-900-topic-1-question-16-discussion/, data_id = 805039
url=/discussions/microsoft/view/56306-exam-az-900-topic-1-question-17-discussion/, data_id = 805040
url=/discussions/microsoft/view/56893-exam-az-900-topic-1-question-18-discussion/, data_id = 805041
url=/discussions/microsoft/view/56634-exam-az-900-topic-1-question-19-discussion/, data_id = 805042
url=/discussions/microsoft/view/56636-exam-az-900-topic-1-question-20-discussion/, data_id = 805043
url=/discussions/microsoft/view/56635-exam-az-900-topic-1-question-21-discussion/, data_id = 805044
url=/discussions/microsoft/view/56637-exam-az-900-topic-1-question-22-discussion/, data_id = 805045
url=/discussions/microsoft/view/56899-exam-az-900-topic-1-question-23-discussion/, data_id = 805046
url=/discussions/microsoft/view/56826-exam-az-900-topic-1-question-24-discussion/, data_id = 805047
url=/discussions/microsoft/view/56641-exam-az-900-topic-1-question-25-discussion/, data_id = 805048
url=/discussions/microsoft/view/56643-exam-az-900-topic-1-question-26-discussion/, data_id = 805049
url=/discussions/microsoft/view/62797-exam-az-900-topic-1-question-27-discussion/, data_id = 805050
url=/discussions/microsoft/view/62807-exam-az-900-topic-1-question-28-discussion/, data_id = 805051
url=/discussions/microsoft/view/56650-exam-az-900-topic-1-question-29-discussion/, data_id = 805052
url=/discussions/microsoft/view/56651-exam-az-900-topic-1-question-30-discussion/, data_id = 805053
url=/discussions/microsoft/view/56915-exam-az-900-topic-1-question-31-discussion/, data_id = 805054
url=/discussions/microsoft/view/56358-exam-az-900-topic-1-question-32-discussion/, data_id = 805055
url=/discussions/microsoft/view/56317-exam-az-900-topic-1-question-33-discussion/, data_id = 805056
url=/discussions/microsoft/view/8931-exam-az-900-topic-1-question-34-discussion/, data_id = 805057
url=/discussions/microsoft/view/9153-exam-az-900-topic-1-question-35-discussion/, data_id = 805058
url=/discussions/microsoft/view/43997-exam-az-900-topic-1-question-36-discussion/, data_id = 805059
url=/discussions/microsoft/view/5731-exam-az-900-topic-1-question-37-discussion/, data_id = 805060
url=/discussions/microsoft/view/44356-exam-az-900-topic-1-question-38-discussion/, data_id = 805061
url=/discussions/microsoft/view/5733-exam-az-900-topic-1-question-39-discussion/, data_id = 805062
url=/discussions/microsoft/view/44357-exam-az-900-topic-1-question-40-discussion/, data_id = 805063
url=/discussions/microsoft/view/44358-exam-az-900-topic-1-question-41-discussion/, data_id = 805064
url=/discussions/microsoft/view/44823-exam-az-900-topic-1-question-42-discussion/, data_id = 805065
url=/discussions/microsoft/view/44053-exam-az-900-topic-1-question-43-discussion/, data_id = 805066
url=/discussions/microsoft/view/5737-exam-az-900-topic-1-question-44-discussion/, data_id = 805067
url=/discussions/microsoft/view/5062-exam-az-900-topic-1-question-45-discussion/, data_id = 805068
url=/discussions/microsoft/view/9155-exam-az-900-topic-1-question-46-discussion/, data_id = 805069
url=/discussions/microsoft/view/5738-exam-az-900-topic-1-question-47-discussion/, data_id = 805070
url=/discussions/microsoft/view/9147-exam-az-900-topic-1-question-48-discussion/, data_id = 805071
url=/discussions/microsoft/view/45659-exam-az-900-topic-1-question-49-discussion/, data_id = 805072
url=/discussions/microsoft/view/44018-exam-az-900-topic-1-question-50-discussion/, data_id = 805073
url=/discussions/microsoft/view/47158-exam-az-900-topic-1-question-51-discussion/, data_id = 805074
url=/discussions/microsoft/view/122824-exam-az-900-topic-1-question-52-discussion/, data_id = 895018
url=/discussions/microsoft/view/9591-exam-az-900-topic-1-question-53-discussion/, data_id = 805076
url=/discussions/microsoft/view/44535-exam-az-900-topic-1-question-54-discussion/, data_id = 805077
url=/discussions/microsoft/view/44148-exam-az-900-topic-1-question-55-discussion/, data_id = 805078
url=/discussions/microsoft/view/46420-exam-az-900-topic-1-question-56-discussion/, data_id = 805079
url=/discussions/microsoft/view/62811-exam-az-900-topic-1-question-57-discussion/, data_id = 805080
url=/discussions/microsoft/view/53855-exam-az-900-topic-1-question-58-discussion/, data_id = 805081
url=/discussions/microsoft/view/15451-exam-az-900-topic-1-question-59-discussion/, data_id = 805082
url=/discussions/microsoft/view/46487-exam-az-900-topic-1-question-60-discussion/, data_id = 805083
url=/discussions/microsoft/view/47470-exam-az-900-topic-1-question-61-discussion/, data_id = 805084
url=/discussions/microsoft/view/44411-exam-az-900-topic-1-question-62-discussion/, data_id = 805085
url=/discussions/microsoft/view/46760-exam-az-900-topic-1-question-63-discussion/, data_id = 805086
url=/discussions/microsoft/view/44583-exam-az-900-topic-1-question-64-discussion/, data_id = 805087
url=/discussions/microsoft/view/44339-exam-az-900-topic-1-question-65-discussion/, data_id = 805088
url=/discussions/microsoft/view/20442-exam-az-900-topic-1-question-66-discussion/, data_id = 805089
url=/discussions/microsoft/view/47673-exam-az-900-topic-1-question-67-discussion/, data_id = 805090
url=/discussions/microsoft/view/45120-exam-az-900-topic-1-question-68-discussion/, data_id = 805091
url=/discussions/microsoft/view/51582-exam-az-900-topic-1-question-69-discussion/, data_id = 805092
url=/discussions/microsoft/view/51428-exam-az-900-topic-1-question-70-discussion/, data_id = 805093
url=/discussions/microsoft/view/53847-exam-az-900-topic-1-question-71-discussion/, data_id = 805094
url=/discussions/microsoft/view/121213-exam-az-900-topic-1-question-72-discussion/, data_id = 895017
url=/discussions/microsoft/view/53938-exam-az-900-topic-1-question-73-discussion/, data_id = 805096
url=/discussions/microsoft/view/61114-exam-az-900-topic-1-question-74-discussion/, data_id = 805097
url=/discussions/microsoft/view/61176-exam-az-900-topic-1-question-75-discussion/, data_id = 805098
url=/discussions/microsoft/view/61344-exam-az-900-topic-1-question-76-discussion/, data_id = 805099
url=/discussions/microsoft/view/62998-exam-az-900-topic-1-question-77-discussion/, data_id = 805100
url=/discussions/microsoft/view/68980-exam-az-900-topic-1-question-78-discussion/, data_id = 805101
url=/discussions/microsoft/view/79523-exam-az-900-topic-1-question-79-discussion/, data_id = 805102
url=/discussions/microsoft/view/81510-exam-az-900-topic-1-question-80-discussion/, data_id = 805103
url=/discussions/microsoft/view/78358-exam-az-900-topic-1-question-81-discussion/, data_id = 805104
url=/discussions/microsoft/view/78398-exam-az-900-topic-1-question-82-discussion/, data_id = 805105
url=/discussions/microsoft/view/78464-exam-az-900-topic-1-question-83-discussion/, data_id = 805106
url=/discussions/microsoft/view/136651-exam-az-900-topic-1-question-462-discussion/, data_id = 912853
url=/discussions/microsoft/view/78624-exam-az-900-topic-1-question-85-discussion/, data_id = 805108
url=/discussions/microsoft/view/80048-exam-az-900-topic-1-question-86-discussion/, data_id = 805109
url=/discussions/microsoft/view/80244-exam-az-900-topic-1-question-87-discussion/, data_id = 805110
url=/discussions/microsoft/view/83342-exam-az-900-topic-1-question-88-discussion/, data_id = 805111
url=/discussions/microsoft/view/119727-exam-az-900-topic-1-question-449-discussion/, data_id = 895016
url=/discussions/microsoft/view/79401-exam-az-900-topic-1-question-90-discussion/, data_id = 805113
url=/discussions/microsoft/view/78399-exam-az-900-topic-1-question-91-discussion/, data_id = 805114
url=/discussions/microsoft/view/78787-exam-az-900-topic-1-question-92-discussion/, data_id = 805115
url=/discussions/microsoft/view/82618-exam-az-900-topic-1-question-93-discussion/, data_id = 805116
url=/discussions/microsoft/view/80769-exam-az-900-topic-1-question-94-discussion/, data_id = 805117
url=/discussions/microsoft/view/78779-exam-az-900-topic-1-question-95-discussion/, data_id = 805118
url=/discussions/microsoft/view/11601-exam-az-900-topic-1-question-96-discussion/, data_id = 805119
url=/discussions/microsoft/view/61122-exam-az-900-topic-1-question-97-discussion/, data_id = 805120
url=/discussions/microsoft/view/9953-exam-az-900-topic-1-question-98-discussion/, data_id = 805121
url=/discussions/microsoft/view/45536-exam-az-900-topic-1-question-99-discussion/, data_id = 805122
url=/discussions/microsoft/view/44003-exam-az-900-topic-1-question-100-discussion/, data_id = 805123
url=/discussions/microsoft/view/7698-exam-az-900-topic-1-question-101-discussion/, data_id = 805124
url=/discussions/microsoft/view/20073-exam-az-900-topic-1-question-102-discussion/, data_id = 805125
url=/discussions/microsoft/view/45977-exam-az-900-topic-1-question-103-discussion/, data_id = 805126
url=/discussions/microsoft/view/7785-exam-az-900-topic-1-question-105-discussion/, data_id = 805128
url=/discussions/microsoft/view/8446-exam-az-900-topic-1-question-106-discussion/, data_id = 805129
url=/discussions/microsoft/view/7995-exam-az-900-topic-1-question-107-discussion/, data_id = 805130
url=/discussions/microsoft/view/47314-exam-az-900-topic-1-question-108-discussion/, data_id = 805131
url=/discussions/microsoft/view/11144-exam-az-900-topic-1-question-110-discussion/, data_id = 805133
url=/discussions/microsoft/view/3205-exam-az-900-topic-1-question-111-discussion/, data_id = 805134
url=/discussions/microsoft/view/44752-exam-az-900-topic-1-question-112-discussion/, data_id = 805135
url=/discussions/microsoft/view/62833-exam-az-900-topic-1-question-113-discussion/, data_id = 805136
url=/discussions/microsoft/view/44761-exam-az-900-topic-1-question-114-discussion/, data_id = 805137
url=/discussions/microsoft/view/45069-exam-az-900-topic-1-question-115-discussion/, data_id = 805138
url=/discussions/microsoft/view/9652-exam-az-900-topic-1-question-116-discussion/, data_id = 805139
url=/discussions/microsoft/view/45324-exam-az-900-topic-1-question-117-discussion/, data_id = 805140
url=/discussions/microsoft/view/52366-exam-az-900-topic-1-question-118-discussion/, data_id = 805141
url=/discussions/microsoft/view/44436-exam-az-900-topic-1-question-119-discussion/, data_id = 805142
url=/discussions/microsoft/view/6408-exam-az-900-topic-1-question-120-discussion/, data_id = 805143
url=/discussions/microsoft/view/44258-exam-az-900-topic-1-question-121-discussion/, data_id = 805144
url=/discussions/microsoft/view/4466-exam-az-900-topic-1-question-122-discussion/, data_id = 805145
url=/discussions/microsoft/view/51304-exam-az-900-topic-1-question-123-discussion/, data_id = 805146
url=/discussions/microsoft/view/51489-exam-az-900-topic-1-question-124-discussion/, data_id = 805147
url=/discussions/microsoft/view/51886-exam-az-900-topic-1-question-125-discussion/, data_id = 805148
url=/discussions/microsoft/view/53294-exam-az-900-topic-1-question-126-discussion/, data_id = 805149
url=/discussions/microsoft/view/44033-exam-az-900-topic-1-question-127-discussion/, data_id = 805150
url=/discussions/microsoft/view/135162-exam-az-900-topic-1-question-461-discussion/, data_id = 912852
url=/discussions/microsoft/view/121427-exam-az-900-topic-1-question-129-discussion/, data_id = 895015
url=/discussions/microsoft/view/54067-exam-az-900-topic-1-question-130-discussion/, data_id = 805153
url=/discussions/microsoft/view/54052-exam-az-900-topic-1-question-131-discussion/, data_id = 805154
url=/discussions/microsoft/view/45560-exam-az-900-topic-1-question-132-discussion/, data_id = 805155
url=/discussions/microsoft/view/61255-exam-az-900-topic-1-question-133-discussion/, data_id = 805156
url=/discussions/microsoft/view/63081-exam-az-900-topic-1-question-134-discussion/, data_id = 805157
url=/discussions/microsoft/view/69096-exam-az-900-topic-1-question-135-discussion/, data_id = 805158
url=/discussions/microsoft/view/69775-exam-az-900-topic-1-question-136-discussion/, data_id = 805159
url=/discussions/microsoft/view/68715-exam-az-900-topic-1-question-137-discussion/, data_id = 805160
url=/discussions/microsoft/view/79913-exam-az-900-topic-1-question-138-discussion/, data_id = 805161
url=/discussions/microsoft/view/79690-exam-az-900-topic-1-question-140-discussion/, data_id = 805163
url=/discussions/microsoft/view/79915-exam-az-900-topic-1-question-141-discussion/, data_id = 805164
url=/discussions/microsoft/view/80311-exam-az-900-topic-1-question-142-discussion/, data_id = 805165
url=/discussions/microsoft/view/82429-exam-az-900-topic-1-question-143-discussion/, data_id = 805166
url=/discussions/microsoft/view/79916-exam-az-900-topic-1-question-144-discussion/, data_id = 805167
url=/discussions/microsoft/view/52910-exam-az-900-topic-1-question-145-discussion/, data_id = 805168
url=/discussions/microsoft/view/84410-exam-az-900-topic-1-question-146-discussion/, data_id = 805169
url=/discussions/microsoft/view/83522-exam-az-900-topic-1-question-147-discussion/, data_id = 805170
url=/discussions/microsoft/view/84412-exam-az-900-topic-1-question-148-discussion/, data_id = 805171
url=/discussions/microsoft/view/82794-exam-az-900-topic-1-question-149-discussion/, data_id = 805172
url=/discussions/microsoft/view/80708-exam-az-900-topic-1-question-150-discussion/, data_id = 805173
url=/discussions/microsoft/view/81560-exam-az-900-topic-1-question-151-discussion/, data_id = 805174
url=/discussions/microsoft/view/44259-exam-az-900-topic-1-question-152-discussion/, data_id = 805175
url=/discussions/microsoft/view/9194-exam-az-900-topic-1-question-153-discussion/, data_id = 805176
url=/discussions/microsoft/view/11135-exam-az-900-topic-1-question-154-discussion/, data_id = 805177
url=/discussions/microsoft/view/4948-exam-az-900-topic-1-question-155-discussion/, data_id = 805178
url=/discussions/microsoft/view/83758-exam-az-900-topic-1-question-156-discussion/, data_id = 805179
url=/discussions/microsoft/view/78635-exam-az-900-topic-1-question-157-discussion/, data_id = 805180
url=/discussions/microsoft/view/84026-exam-az-900-topic-1-question-158-discussion/, data_id = 805181
url=/discussions/microsoft/view/10023-exam-az-900-topic-1-question-159-discussion/, data_id = 805182
url=/discussions/microsoft/view/10808-exam-az-900-topic-1-question-160-discussion/, data_id = 805183
url=/discussions/microsoft/view/12156-exam-az-900-topic-1-question-161-discussion/, data_id = 805184
url=/discussions/microsoft/view/84024-exam-az-900-topic-1-question-162-discussion/, data_id = 805185
url=/discussions/microsoft/view/84471-exam-az-900-topic-1-question-163-discussion/, data_id = 805186
url=/discussions/microsoft/view/3203-exam-az-900-topic-1-question-164-discussion/, data_id = 805187
url=/discussions/microsoft/view/2971-exam-az-900-topic-1-question-165-discussion/, data_id = 805188
url=/discussions/microsoft/view/45182-exam-az-900-topic-1-question-166-discussion/, data_id = 805189
url=/discussions/microsoft/view/12298-exam-az-900-topic-1-question-167-discussion/, data_id = 805190
url=/discussions/microsoft/view/44024-exam-az-900-topic-1-question-168-discussion/, data_id = 805191
url=/discussions/microsoft/view/44734-exam-az-900-topic-1-question-169-discussion/, data_id = 805192
url=/discussions/microsoft/view/44741-exam-az-900-topic-1-question-170-discussion/, data_id = 805193
url=/discussions/microsoft/view/11191-exam-az-900-topic-1-question-171-discussion/, data_id = 805194
url=/discussions/microsoft/view/44742-exam-az-900-topic-1-question-172-discussion/, data_id = 805195
url=/discussions/microsoft/view/9991-exam-az-900-topic-1-question-173-discussion/, data_id = 805196
url=/discussions/microsoft/view/12323-exam-az-900-topic-1-question-174-discussion/, data_id = 805197
url=/discussions/microsoft/view/8995-exam-az-900-topic-1-question-175-discussion/, data_id = 805198
url=/discussions/microsoft/view/5647-exam-az-900-topic-1-question-176-discussion/, data_id = 805199
url=/discussions/microsoft/view/11131-exam-az-900-topic-1-question-177-discussion/, data_id = 805200
url=/discussions/microsoft/view/9301-exam-az-900-topic-1-question-178-discussion/, data_id = 805201
url=/discussions/microsoft/view/48007-exam-az-900-topic-1-question-179-discussion/, data_id = 805202
url=/discussions/microsoft/view/46384-exam-az-900-topic-1-question-180-discussion/, data_id = 805203
url=/discussions/microsoft/view/47125-exam-az-900-topic-1-question-181-discussion/, data_id = 805204
url=/discussions/microsoft/view/69479-exam-az-900-topic-1-question-182-discussion/, data_id = 805205
url=/discussions/microsoft/view/8755-exam-az-900-topic-1-question-183-discussion/, data_id = 805206
url=/discussions/microsoft/view/9162-exam-az-900-topic-1-question-184-discussion/, data_id = 805207
url=/discussions/microsoft/view/44038-exam-az-900-topic-1-question-185-discussion/, data_id = 805208
url=/discussions/microsoft/view/44185-exam-az-900-topic-1-question-186-discussion/, data_id = 805209
url=/discussions/microsoft/view/9632-exam-az-900-topic-1-question-187-discussion/, data_id = 805210
url=/discussions/microsoft/view/51502-exam-az-900-topic-1-question-188-discussion/, data_id = 805211
url=/discussions/microsoft/view/45073-exam-az-900-topic-1-question-189-discussion/, data_id = 805212
url=/discussions/microsoft/view/45074-exam-az-900-topic-1-question-190-discussion/, data_id = 805213
url=/discussions/microsoft/view/44117-exam-az-900-topic-1-question-191-discussion/, data_id = 805214
url=/discussions/microsoft/view/45075-exam-az-900-topic-1-question-192-discussion/, data_id = 805215
url=/discussions/microsoft/view/51980-exam-az-900-topic-1-question-193-discussion/, data_id = 805216
url=/discussions/microsoft/view/53894-exam-az-900-topic-1-question-194-discussion/, data_id = 805217
url=/discussions/microsoft/view/45076-exam-az-900-topic-1-question-195-discussion/, data_id = 805218
url=/discussions/microsoft/view/9649-exam-az-900-topic-1-question-196-discussion/, data_id = 805219
url=/discussions/microsoft/view/63075-exam-az-900-topic-1-question-197-discussion/, data_id = 805220
url=/discussions/microsoft/view/69583-exam-az-900-topic-1-question-198-discussion/, data_id = 805221
url=/discussions/microsoft/view/80968-exam-az-900-topic-1-question-199-discussion/, data_id = 805222
url=/discussions/microsoft/view/138800-exam-az-900-topic-1-question-459-discussion/, data_id = 912850
url=/discussions/microsoft/view/84319-exam-az-900-topic-1-question-201-discussion/, data_id = 805224
url=/discussions/microsoft/view/14896-exam-az-900-topic-1-question-202-discussion/, data_id = 805225

In [ ]:
def open_page(driver, url):
    discuss_url = 'https://www.examtopics.com' + str(url) + '/'
    # discuss_url = 'https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id=35981'
    page = driver.get(discuss_url)
    time.sleep(randint(1, 5))
    return page

In [ ]:
# Define formatting function
def format_column(column, length, column_type):
    if column_type == 'string':
        return column.ljust(length)  # Left-align string columns
    elif column_type == 'int':
        return str(column).rjust(length)  # Right-align integer columns
    else:
        return column

# Define column lengths and types
column_lengths = [70, 5, 8, 20, 120]
column_types = ['string', 'int', 'int', 'string', 'string']

# Open the file in write mode
filename = 'output.txt'
with open(filename, 'w') as file:
    # Write data rows
    for _, row in df.iterrows():
        formatted_row = [format_column(row[col], length, col_type) for col, length, col_type in zip(df.columns, column_lengths, column_types)]
        file.write('\t'.join(formatted_row) + '\n')

:

In [4]:
    driver.quit()

In [ ]:
def open_isacadiscuss(driver, pageno):
    discuss_url = 'https://www.examtopics.com/discussions/isaca/' + str(pageno) + '/'
    # discuss_url = 'https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id=35981'
    page = driver.get(discuss_url)
    time.sleep(randint(1, 5))
    return

In [ ]:
if __name__ == "__main__":
    driver = set_chrome_driver()

    driver.set_window_position(1800,10)
    
    with open("IsacaDiscussList.txt", "a", encoding='utf-8') as file:    
        for i in range(254)[:2]:
            pageno = i + 1

            open_isacadiscuss(driver, pageno)

            driver.switch_to.window(driver.window_handles[0])
            print(driver.title + "-" + str(pageno))
            bs = BeautifulSoup(driver.page_source, 'html.parser')
            div_card = bs.find_all("div", {"class": "container-fluid discussion-list"})
            a = bs.find_all("a", {"class": "discussion-link"})
            span = bs.find_all("span", {"class": "recent-post-time"})
            for i in range(len(a)):
                last_post = parser.parse(str(span[i*2+1]["title"]).replace("midnight", "12:00 a.m.").replace("noon", "12:00 p.m."))
                split_text = str(a[i].text.strip()).split()

                question = ' '.join(split_text[:5])
                number = split_text[5]
                discussion = split_text[6]
                did = str(a[i]["href"]).split('/')[4].split('-')[0]
                
                
                file.write(question+"\t"+str(number)+"\t"+discussion+"\t"+str(last_post)+"\t"+str(a[i]["href"])+"\t"+did+"\n")                   

    file.close()
    
    driver.quit()

Isaca discussions - ExamTopics Forum-1
Isaca discussions - ExamTopics Forum-2

In [ ]:
    pageno = 1
    print(driver.title + " - " + str(pageno))

    bs = BeautifulSoup(driver.page_source, 'html.parser')
    div_card = bs.find_all("div", {"class": "container-fluid discussion-list"})
    a = bs.find_all("a", {"class": "discussion-link"})
    span = bs.find_all("span", {"class": "recent-post-time"})
    for i in range(len(a)):
        last_post = parser.parse(str(span[i*2+1]["title"]))
        print(str(a[i].text.strip())+"\t"+str(last_post)+"\t"+str(a[i]["href"])+"\n")
        #print(str(last_post)+"\t")
        #print(str(a[i]["href"])+"\n")

Isaca discussions - ExamTopics Forum - 1
Exam CISM topic 1 question 820 discussion	2023-07-08 20:40:00	/discussions/isaca/view/114534-exam-cism-topic-1-question-820-discussion/

Exam CISM topic 1 question 451 discussion	2023-07-08 19:51:00	/discussions/isaca/view/113467-exam-cism-topic-1-question-451-discussion/

Exam CISM topic 1 question 337 discussion	2023-07-08 18:11:00	/discussions/isaca/view/94539-exam-cism-topic-1-question-337-discussion/

Exam CISA topic 1 question 303 discussion	2023-07-08 16:19:00	/discussions/isaca/view/108648-exam-cisa-topic-1-question-303-discussion/

Exam CISM topic 1 question 312 discussion	2023-07-08 14:51:00	/discussions/isaca/view/106125-exam-cism-topic-1-question-312-discussion/

Exam CISM topic 1 question 203 discussion	2023-07-08 12:31:00	/discussions/isaca/view/98947-exam-cism-topic-1-question-203-discussion/

Exam CRISC topic 1 question 410 discussion	2023-07-08 05:53:00	/discussions/isaca/view/54147-exam-crisc-topic-1-question-410-discussion/

Exam CISA topic 1 question 261 discussion	2023-07-08 04:42:00	/discussions/isaca/view/114474-exam-cisa-topic-1-question-261-discussion/

Exam CISM topic 1 question 779 discussion	2023-07-07 18:31:00	/discussions/isaca/view/110737-exam-cism-topic-1-question-779-discussion/

Exam CRISC topic 1 question 826 discussion	2023-07-07 18:28:00	/discussions/isaca/view/43354-exam-crisc-topic-1-question-826-discussion/

Exam CISA topic 1 question 657 discussion	2023-07-07 18:21:00	/discussions/isaca/view/91552-exam-cisa-topic-1-question-657-discussion/

Exam CISA topic 1 question 649 discussion	2023-07-07 17:57:00	/discussions/isaca/view/114440-exam-cisa-topic-1-question-649-discussion/

Exam CISM topic 1 question 305 discussion	2023-07-07 16:32:00	/discussions/isaca/view/111227-exam-cism-topic-1-question-305-discussion/

Exam CISA topic 1 question 218 discussion	2023-07-07 16:12:00	/discussions/isaca/view/114435-exam-cisa-topic-1-question-218-discussion/

Exam CISM topic 1 question 303 discussion	2023-07-07 16:01:00	/discussions/isaca/view/87214-exam-cism-topic-1-question-303-discussion/

Exam CISM topic 1 question 227 discussion	2023-07-07 15:53:00	/discussions/isaca/view/104926-exam-cism-topic-1-question-227-discussion/

Exam CISM topic 1 question 217 discussion	2023-07-07 15:43:00	/discussions/isaca/view/88455-exam-cism-topic-1-question-217-discussion/

Exam CISM topic 1 question 198 discussion	2023-07-07 15:21:00	/discussions/isaca/view/98688-exam-cism-topic-1-question-198-discussion/

Exam CISM topic 1 question 411 discussion	2023-07-07 12:26:00	/discussions/isaca/view/113039-exam-cism-topic-1-question-411-discussion/

Exam CISM topic 1 question 18 discussion	2023-07-07 11:55:00	/discussions/isaca/view/38094-exam-cism-topic-1-question-18-discussion/

In [ ]:
               
    driver.quit()

In [ ]:
fname = 'DBS/DBS-Q000.html'

with open(fname, "r", encoding='utf-8') as file:
    html = file.read()
    file.close()
        
#print(html)
bs_template = BeautifulSoup(html, 'html.parser')

bs_template

<!DOCTYPE html>
<html lang="en">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<base href="https://changwhaj.github.io/assets/"/>
</head>
<body class="home2"><div style="position:relative;">
<!-- RubyOnRails - formstatic / kaminari -->
<meta content="authenticity_token" name="csrf-param"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-119892649-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-119892649-1');
</script>
<!-- meta tag -->
<meta charset="utf-8"/>
<title>Exam AWS Certified Database - Specialty topic 1 question 250 discussion - ExamTopics</title>
<!-- responsive tag -->
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- favicon -->
<link href="/assets/images/et/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/assets/images/et/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/assets/images/et/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/assets/images/et/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/assets/images/et/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/assets/images/et/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/assets/images/et/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/assets/images/et/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/assets/images/et/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/assets/images/et/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/assets/images/et/favicon/manifest.json" rel="manifest"/>
<meta content="#007bff" name="msapplication-TileColor"/>
<meta content="/assets/images/et/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- deflink == defered link (loaded later by jquery) -->
<!-- bootstrap v4 css -->
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<!-- font-awesome css -->
<link defhref="/assets/css/font-awesome.min.css" href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<!-- animate css -->
<link defhref="/assets/css/animate.css" href="/assets/css/animate.css" rel="stylesheet" type="text/css"/>
<!-- owl.carousel css -->
<link defhref="/assets/css/owl.carousel.css" href="/assets/css/owl.carousel.css" rel="stylesheet" type="text/css"/>
<!-- slick css -->
<link defhref="/assets/css/slick.css" href="/assets/css/slick.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu CSS -->
<link href="/assets/css/rsmenu-main.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu transitions CSS -->
<link defhref="/assets/css/rsmenu-transitions.css" href="/assets/css/rsmenu-transitions.css" rel="stylesheet" type="text/css"/>
<!-- magnific popup css -->
<link defhref="/assets/css/magnific-popup.css" href="/assets/css/magnific-popup.css" rel="stylesheet" type="text/css"/>
<!-- flaticon css  -->
<link defhref="/assets/fonts/flaticon.css" href="/assets/fonts/flaticon.css" rel="stylesheet" type="text/css"/>
<!-- flaticon2 css  -->
<link defhref="/assets/fonts/fonts2/flaticon.css" href="/assets/fonts/fonts2/flaticon.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/style.css?ver=1" rel="stylesheet" type="text/css"/>
<link href="/assets/css/color/default.css" rel="stylesheet" type="text/css"/>
<!-- responsive css -->
<link href="/assets/css/responsive.css" rel="stylesheet" type="text/css"/>
<meta content="”NOARCHIVE”" name="”ROBOTS”"/>
<link href="/assets/css/forum.css" rel="stylesheet" type="text/css"/>
<style>
</style>
<div class="sec-spacer pt-50">
<div class="container">
<!-- BEGIN Discussions header / title -->
<div class="row">
<div class="col-12">
<div class="discussion-list-header">
<h1><i class="fa fa-file-text-o mr-3"></i>Exam AWS ...</h1>
</div>
</div>
</div>
<!-- END Discussions header / title -->
<!-- BEGIN Discussion Content -->
<div class="row">
<div class="col-12">
<div class="discussion-header-container">
<!-- Question -->
<div class="question-discussion-header">

                                    Exam question from

                                Amazon's
<div>
                                    Question #: <br/>
                                    Topic #:
                                </div>
</div>
<div class="question-body mt-3 pt-3 border-top" data-id="807492">
<p class="card-text">

                                        A ...<br/>
</p>
<div class="voted-answers-tally d-none">
<script id="807492" type="application/json">[{"voted_answers": "B", "vote_count": 1, "is_most_voted": false}]</script>
</div>
<div class="question-choices-container">
<ul>
<li class="multi-choice-item correct-hidden">
<span class="multi-choice-letter" data-choice-letter="A">
                                                            A.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="B">
                                                            B.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="C">
                                                            C.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="D">
                                                            D.
                                                        </span>

                                                    ...
                                                </li>
</ul>
</div>
<a class="btn btn-primary reveal-solution" href="#">Show Suggested Answer</a>
<a class="btn btn-primary hide-solution d-none" href="#">Hide Answer</a>
<div class="card-text question-answer bg-light white-text">
<span class="correct-answer-box"><strong>Suggested Answer:</strong>
<span class="correct-answer">A</span>
<br/>
</span>
<span class="answer-description">
</span>
<div class="voting-summary col-12 col-sm-6 col-lg-4 pt-2 pb-2" style="font-size: 0.9em"><i>Community vote distribution</i><!-- Additional optional vote button: <a href="javascript:void(0)" data-toggle="tooltip" class="vote-answer-button" title="Vote an answer">🗳️</a>--><div class="progress vote-distribution-bar"><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" class="vote-bar progress-bar bg-primary" data-original-title="1 votes." data-toggle="tooltip" role="progressbar" style="width: 100%; display: flex;" title="">B (100%)</div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-info" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">C (25%)
                </div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-success" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">B (20%)
                </div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" class="vote-bar progress-bar bg-warning" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 15%; display: none;" title="">Other
                </div></div></div></div>
</div>
<!-- / Question  -->
<div class="discussion-meta-data mt-3 pt-1 border-top">
...
</div>
</div>
<div class="discussion-page-comments-section" data-discussion-question-id="807492">
<div class="mt-4 ml-2 font-"><h4 class="mb-0" id="comment-section-title">Comments</h4></div>
<!-- Discussion start -->
<div class="container outer-discussion-container">
...
</div>
<!-- Discussion end -->
</div>
</div>
</div>
<!-- END Discussion Content -->
</div>
</div>
<!-- start scrollUp  -->
<div class="d-print-none" id="scrollUp">
<i class="fa fa-angle-up"></i>
</div>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- modernizr js -->
<script src="/assets/js/modernizr-2.8.3.min.js"></script>
<!-- jquery latest version -->
<script src="/assets/js/jquery.min.js"></script>
<!-- bootstrap js -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- owl.carousel js
        <script src="/assets/js/owl.carousel.min.js"></script>-->
<!-- slick.min js -->
<script src="/assets/js/slick.min.js"></script>
<!-- isotope.pkgd.min js -->
<script src="/assets/js/isotope.pkgd.min.js"></script>
<!-- imagesloaded.pkgd.min js -->
<script src="/assets/js/imagesloaded.pkgd.min.js"></script>
<!-- wow js -->
<script src="/assets/js/wow.min.js"></script>
<!-- counter top js -->
<script src="/assets/js/waypoints.min.js"></script>
<script src="/assets/js/jquery.counterup.min.js"></script>
<!-- magnific popup -->
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<!-- rsmenu js -->
<script src="/assets/js/rsmenu-main.js"></script>
<!-- plugins js -->
<script src="/assets/js/plugins.js"></script>
<!-- Switch js -->
<script src="/assets/js/color-style.js"></script>
<!-- main js -->
<script src="/assets/js/main.js"></script>
<script src="/assets/js/bootbox.min.js"></script>
<script async="" defer="" src="/assets/js/bootstrap3-typeahead.min.js">
</script>
<script type="text/javascript">
    // Activate tooltips
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    })

    $(document).ready(function () {
        // Load stylesheets in a deferred way:
        $('link[defhref]').each(function() {
            $(this).attr('href', $(this).attr('defhref'));
            //var src = $(this).attr('href');
            //loadStyleSheet(src);
        });

        // Load mobile images in a deferred way:
        var isMobile = window.matchMedia("only screen and (max-width: 490px)").matches;
        if (isMobile) {
            $('img[mobile-defsrc]').each(function () {
                $(this).attr('src', $(this).attr('mobile-defsrc')).removeAttr('defsrc');
            });
        }

        // Load images in a deferred way:
        $('img[defsrc]').each(function() {
            $(this).attr('src',$(this).attr('defsrc'));
        });


        function delayedStart() {
            // Typeahead start

            // Register typeahead element:
            $('#header-keyword-search, #modal-keyword-search').typeahead({
                source: autoCompleteQuery,
                autoSelect: true,
                delay: 150,
                selectOnBlur: false,
                afterSelect: function(param) {$(this.$element).closest('form').submit()}
            });

            // Query ajax function:
            function autoCompleteQuery(query, callback) {
                return $.get("/ajax/autocomplete/suggestions/?query=" + query).done(callback);
            }
            // Typeahead end
        }
        setTimeout(delayedStart, 1500);

        // Don't submit empty search query
        $('#modal-keyword-search-form').submit(function() {
            if (!$('#modal-keyword-search').val()) {
                return false;
            }
        });

        // Auto focus on search box when search-modal is opened
        $('.search-modal').on('shown.bs.modal', function (e) {
            $(this).find('input[type=text]').focus();
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function (){
        set_voting_configuration_by_question($(".question-body"));
    });
</script>
<input class="csrf-value" type="hidden" value=""/><!-- Moderate actions: -->
<script type="text/javascript">
    // Approve:
    $("body").on("click", ".approve-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "approve");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else {
            $(this).closest(".media").find(".approve-comment-button").slideUp();
            $(this).closest(".media").find(".comment-head-notification").text("");
        }
    });

    // Delete:
    $("body").on("click", ".delete-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "delete");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Bump:
    $("body").on("click", ".bump-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "bump");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Edit open:
    $("body").on("click", ".edit-comment-button", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var comment_original_text = comment_content_div.text();

        var edit_comment_content = $("#edit-comment-template").html();

        comment_content_div.text("");
        comment_content_div.html(edit_comment_content);

        comment_content_div.find(".original-comment").text(comment_original_text);
        textarea = comment_content_div.find("textarea")
        textarea.text(comment_original_text);
        autoresize(textarea);
    });

    // Edit cancel:
    $("body").on("click", ".comment-edit-cancel", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var original_comment_content = comment_content_div.find(".original-comment").text();
        comment_content_div.html(original_comment_content);
    });

    // Edit save:
    $("body").on("click", ".comment-edit-save", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var new_comment_content = comment_content_div.find("textarea").val();

        moderate_comment(comment_id, "edit", new_comment_content);
        comment_content_div.html(new_comment_content);
    });

    function moderate_comment(comment_id, action, extra) {
        if (extra === undefined) {
            extra = 1;
        }
        var ajax_data = {
            'comment_id': comment_id,
        };
        ajax_data[action] = extra;

        $.ajax({
            url: "/ajax/moderate/",
            method: 'GET',
            data: ajax_data,
            error: function (xhr, status, error) {
                alert(status.toString() + "," + error.toString() + ":" + xhr.responseText);
            }
        });
    }

    // Auto resize textarea to fit contents:
    function autoresize(textarea) {
        textarea = $(textarea)
        textarea.css('height','0px');     //Reset height, so that it not only grows but also shrinks
        textarea.css('height',(textarea[0].scrollHeight + 10) + 'px');    //Set new height
    }

    $('textarea.comment-edit').keyup(function () {
        autoresize(this);
    });

    // Handle "Load Full Discussion" button
    $("body").on("click", ".load-full-discussion-button", function (){
        if ($(this).hasClass("disabled"))
            return false;
        $(".load-full-discussion-button").addClass("disabled");
        let after_comment_id = $(this).parents(".load-more-section").data("after-comment");
        let discussion_id = $(this).parents(".load-more-section").data("discussion-id");
        let discussion_load_indicator = $('.full-discussion-loading-spinner').clone()
        let discussion_container = $(this).parents(".outer-discussion-container");
        $(this).replaceWith(discussion_load_indicator);
        discussion_load_indicator.show();

        $.ajax({
            url: "/ajax/discussion/load-complete/",
            method: 'GET',
            dataType: 'html',
            data: {"discussion-id": discussion_id},
            success: function (full_discussion_html) {
                let full_discusssion = $(full_discussion_html);
                discussion_container.replaceWith(full_discusssion);
                // Scroll to the current comment location:
                setTimeout(function() {
                    $(document).scrollTop(
                        $("#comment-"+after_comment_id).offset().top - 80
                    )
                }, 100);
            },
            error: function (xhr, status, error) {
                alert("Error loading full discussion");
            }
        })
    });
</script>
<script src="/assets/js/comments.js?ver=1" type="text/javascript"></script>
<!-- / Comments dependencies -->
<script src="/assets/js/examview.js?ver=4" type="text/javascript"></script>
<!-- End temporary -->
<input class="is-logged-in" type="hidden" value="0"/>
</div></body></html>

In [ ]:
print(str(bs_template).replace('</div>', '</DIV>'))

<!DOCTYPE html>
<html lang="en">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<base href="https://changwhaj.github.io/assets/"/>
</head>
<body class="home2"><div style="position:relative;">
<!-- RubyOnRails - formstatic / kaminari -->
<meta content="authenticity_token" name="csrf-param"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-119892649-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-119892649-1');
</script>
<!-- meta tag -->
<meta charset="utf-8"/>
<title>Exam AWS Certified Database - Specialty topic 1 question 250 discussion - ExamTopics</title>
<!-- responsive tag -->
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- favicon -->
<link href="/assets/images/et/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/assets/images/et/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/assets/images/et/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/assets/images/et/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/assets/images/et/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/assets/images/et/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/assets/images/et/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/assets/images/et/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/assets/images/et/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/assets/images/et/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/assets/images/et/favicon/manifest.json" rel="manifest"/>
<meta content="#007bff" name="msapplication-TileColor"/>
<meta content="/assets/images/et/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- deflink == defered link (loaded later by jquery) -->
<!-- bootstrap v4 css -->
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<!-- font-awesome css -->
<link defhref="/assets/css/font-awesome.min.css" href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<!-- animate css -->
<link defhref="/assets/css/animate.css" href="/assets/css/animate.css" rel="stylesheet" type="text/css"/>
<!-- owl.carousel css -->
<link defhref="/assets/css/owl.carousel.css" href="/assets/css/owl.carousel.css" rel="stylesheet" type="text/css"/>
<!-- slick css -->
<link defhref="/assets/css/slick.css" href="/assets/css/slick.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu CSS -->
<link href="/assets/css/rsmenu-main.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu transitions CSS -->
<link defhref="/assets/css/rsmenu-transitions.css" href="/assets/css/rsmenu-transitions.css" rel="stylesheet" type="text/css"/>
<!-- magnific popup css -->
<link defhref="/assets/css/magnific-popup.css" href="/assets/css/magnific-popup.css" rel="stylesheet" type="text/css"/>
<!-- flaticon css  -->
<link defhref="/assets/fonts/flaticon.css" href="/assets/fonts/flaticon.css" rel="stylesheet" type="text/css"/>
<!-- flaticon2 css  -->
<link defhref="/assets/fonts/fonts2/flaticon.css" href="/assets/fonts/fonts2/flaticon.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/style.css?ver=1" rel="stylesheet" type="text/css"/>
<link href="/assets/css/color/default.css" rel="stylesheet" type="text/css"/>
<!-- responsive css -->
<link href="/assets/css/responsive.css" rel="stylesheet" type="text/css"/>
<meta content="”NOARCHIVE”" name="”ROBOTS”"/>
<link href="/assets/css/forum.css" rel="stylesheet" type="text/css"/>
<style>
</style>
<div class="sec-spacer pt-50">
<div class="container">
<!-- BEGIN Discussions header / title -->
<div class="row">
<div class="col-12">
<div class="discussion-list-header">
<h1><i class="fa fa-file-text-o mr-3"></i>Exam AWS ...</h1>
</DIV>
</DIV>
</DIV>
<!-- END Discussions header / title -->
<!-- BEGIN Discussion Content -->
<div class="row">
<div class="col-12">
<div class="discussion-header-container">
<!-- Question -->
<div class="question-discussion-header">

                                    Exam question from

                                Amazon's
<div>
                                    Question #: <br/>
                                    Topic #:
                                </DIV>
</DIV>
<div class="question-body mt-3 pt-3 border-top" data-id="807492">
<p class="card-text">

                                        A ...<br/>
</p>
<div class="voted-answers-tally d-none">
<script id="807492" type="application/json">[{"voted_answers": "B", "vote_count": 1, "is_most_voted": false}]</script>
</DIV>
<div class="question-choices-container">
<ul>
<li class="multi-choice-item correct-hidden">
<span class="multi-choice-letter" data-choice-letter="A">
                                                            A.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="B">
                                                            B.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="C">
                                                            C.
                                                        </span>

                                                    ...
                                                </li>
<li class="multi-choice-item">
<span class="multi-choice-letter" data-choice-letter="D">
                                                            D.
                                                        </span>

                                                    ...
                                                </li>
</ul>
</DIV>
<a class="btn btn-primary reveal-solution" href="#">Show Suggested Answer</a>
<a class="btn btn-primary hide-solution d-none" href="#">Hide Answer</a>
<div class="card-text question-answer bg-light white-text">
<span class="correct-answer-box"><strong>Suggested Answer:</strong>
<span class="correct-answer">A</span>
<br/>
</span>
<span class="answer-description">
</span>
<div class="voting-summary col-12 col-sm-6 col-lg-4 pt-2 pb-2" style="font-size: 0.9em"><i>Community vote distribution</i><!-- Additional optional vote button: <a href="javascript:void(0)" data-toggle="tooltip" class="vote-answer-button" title="Vote an answer">🗳️</a>--><div class="progress vote-distribution-bar"><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" class="vote-bar progress-bar bg-primary" data-original-title="1 votes." data-toggle="tooltip" role="progressbar" style="width: 100%; display: flex;" title="">B (100%)</DIV><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-info" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">C (25%)
                </DIV><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-success" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">B (20%)
                </DIV><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" class="vote-bar progress-bar bg-warning" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 15%; display: none;" title="">Other
                </DIV></DIV></DIV></DIV>
</DIV>
<!-- / Question  -->
<div class="discussion-meta-data mt-3 pt-1 border-top">
...
</DIV>
</DIV>
<div class="discussion-page-comments-section" data-discussion-question-id="807492">
<div class="mt-4 ml-2 font-"><h4 class="mb-0" id="comment-section-title">Comments</h4></DIV>
<!-- Discussion start -->
<div class="container outer-discussion-container">
...
</DIV>
<!-- Discussion end -->
</DIV>
</DIV>
</DIV>
<!-- END Discussion Content -->
</DIV>
</DIV>
<!-- start scrollUp  -->
<div class="d-print-none" id="scrollUp">
<i class="fa fa-angle-up"></i>
</DIV>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- modernizr js -->
<script src="/assets/js/modernizr-2.8.3.min.js"></script>
<!-- jquery latest version -->
<script src="/assets/js/jquery.min.js"></script>
<!-- bootstrap js -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- owl.carousel js
        <script src="/assets/js/owl.carousel.min.js"></script>-->
<!-- slick.min js -->
<script src="/assets/js/slick.min.js"></script>
<!-- isotope.pkgd.min js -->
<script src="/assets/js/isotope.pkgd.min.js"></script>
<!-- imagesloaded.pkgd.min js -->
<script src="/assets/js/imagesloaded.pkgd.min.js"></script>
<!-- wow js -->
<script src="/assets/js/wow.min.js"></script>
<!-- counter top js -->
<script src="/assets/js/waypoints.min.js"></script>
<script src="/assets/js/jquery.counterup.min.js"></script>
<!-- magnific popup -->
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<!-- rsmenu js -->
<script src="/assets/js/rsmenu-main.js"></script>
<!-- plugins js -->
<script src="/assets/js/plugins.js"></script>
<!-- Switch js -->
<script src="/assets/js/color-style.js"></script>
<!-- main js -->
<script src="/assets/js/main.js"></script>
<script src="/assets/js/bootbox.min.js"></script>
<script async="" defer="" src="/assets/js/bootstrap3-typeahead.min.js">
</script>
<script type="text/javascript">
    // Activate tooltips
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    })

    $(document).ready(function () {
        // Load stylesheets in a deferred way:
        $('link[defhref]').each(function() {
            $(this).attr('href', $(this).attr('defhref'));
            //var src = $(this).attr('href');
            //loadStyleSheet(src);
        });

        // Load mobile images in a deferred way:
        var isMobile = window.matchMedia("only screen and (max-width: 490px)").matches;
        if (isMobile) {
            $('img[mobile-defsrc]').each(function () {
                $(this).attr('src', $(this).attr('mobile-defsrc')).removeAttr('defsrc');
            });
        }

        // Load images in a deferred way:
        $('img[defsrc]').each(function() {
            $(this).attr('src',$(this).attr('defsrc'));
        });


        function delayedStart() {
            // Typeahead start

            // Register typeahead element:
            $('#header-keyword-search, #modal-keyword-search').typeahead({
                source: autoCompleteQuery,
                autoSelect: true,
                delay: 150,
                selectOnBlur: false,
                afterSelect: function(param) {$(this.$element).closest('form').submit()}
            });

            // Query ajax function:
            function autoCompleteQuery(query, callback) {
                return $.get("/ajax/autocomplete/suggestions/?query=" + query).done(callback);
            }
            // Typeahead end
        }
        setTimeout(delayedStart, 1500);

        // Don't submit empty search query
        $('#modal-keyword-search-form').submit(function() {
            if (!$('#modal-keyword-search').val()) {
                return false;
            }
        });

        // Auto focus on search box when search-modal is opened
        $('.search-modal').on('shown.bs.modal', function (e) {
            $(this).find('input[type=text]').focus();
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function (){
        set_voting_configuration_by_question($(".question-body"));
    });
</script>
<input class="csrf-value" type="hidden" value=""/><!-- Moderate actions: -->
<script type="text/javascript">
    // Approve:
    $("body").on("click", ".approve-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "approve");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else {
            $(this).closest(".media").find(".approve-comment-button").slideUp();
            $(this).closest(".media").find(".comment-head-notification").text("");
        }
    });

    // Delete:
    $("body").on("click", ".delete-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "delete");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Bump:
    $("body").on("click", ".bump-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "bump");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Edit open:
    $("body").on("click", ".edit-comment-button", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var comment_original_text = comment_content_div.text();

        var edit_comment_content = $("#edit-comment-template").html();

        comment_content_div.text("");
        comment_content_div.html(edit_comment_content);

        comment_content_div.find(".original-comment").text(comment_original_text);
        textarea = comment_content_div.find("textarea")
        textarea.text(comment_original_text);
        autoresize(textarea);
    });

    // Edit cancel:
    $("body").on("click", ".comment-edit-cancel", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var original_comment_content = comment_content_div.find(".original-comment").text();
        comment_content_div.html(original_comment_content);
    });

    // Edit save:
    $("body").on("click", ".comment-edit-save", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var new_comment_content = comment_content_div.find("textarea").val();

        moderate_comment(comment_id, "edit", new_comment_content);
        comment_content_div.html(new_comment_content);
    });

    function moderate_comment(comment_id, action, extra) {
        if (extra === undefined) {
            extra = 1;
        }
        var ajax_data = {
            'comment_id': comment_id,
        };
        ajax_data[action] = extra;

        $.ajax({
            url: "/ajax/moderate/",
            method: 'GET',
            data: ajax_data,
            error: function (xhr, status, error) {
                alert(status.toString() + "," + error.toString() + ":" + xhr.responseText);
            }
        });
    }

    // Auto resize textarea to fit contents:
    function autoresize(textarea) {
        textarea = $(textarea)
        textarea.css('height','0px');     //Reset height, so that it not only grows but also shrinks
        textarea.css('height',(textarea[0].scrollHeight + 10) + 'px');    //Set new height
    }

    $('textarea.comment-edit').keyup(function () {
        autoresize(this);
    });

    // Handle "Load Full Discussion" button
    $("body").on("click", ".load-full-discussion-button", function (){
        if ($(this).hasClass("disabled"))
            return false;
        $(".load-full-discussion-button").addClass("disabled");
        let after_comment_id = $(this).parents(".load-more-section").data("after-comment");
        let discussion_id = $(this).parents(".load-more-section").data("discussion-id");
        let discussion_load_indicator = $('.full-discussion-loading-spinner').clone()
        let discussion_container = $(this).parents(".outer-discussion-container");
        $(this).replaceWith(discussion_load_indicator);
        discussion_load_indicator.show();

        $.ajax({
            url: "/ajax/discussion/load-complete/",
            method: 'GET',
            dataType: 'html',
            data: {"discussion-id": discussion_id},
            success: function (full_discussion_html) {
                let full_discusssion = $(full_discussion_html);
                discussion_container.replaceWith(full_discusssion);
                // Scroll to the current comment location:
                setTimeout(function() {
                    $(document).scrollTop(
                        $("#comment-"+after_comment_id).offset().top - 80
                    )
                }, 100);
            },
            error: function (xhr, status, error) {
                alert("Error loading full discussion");
            }
        })
    });
</script>
<script src="/assets/js/comments.js?ver=1" type="text/javascript"></script>
<!-- / Comments dependencies -->
<script src="/assets/js/examview.js?ver=4" type="text/javascript"></script>
<!-- End temporary -->
<input class="is-logged-in" type="hidden" value="0"/>
</DIV></body></html>

In [ ]:
import math
QUESTIONS_PER_PAGE = 5
QUESTIONS_TOTAL = 258
PAGE_COUNTS = QUESTIONS_TOTAL / QUESTIONS_PER_PAGE
print(round(QUESTIONS_TOTAL / QUESTIONS_PER_PAGE + 0.5))
math.ceil(1.5)

52

2

In [ ]:
fname = 'DBS/DBS-Q000.html'

with open(fname, "r", encoding='utf-8') as file:
    html = file.read()
    file.close()
        
#print(html)
bs_template = BeautifulSoup(html, 'html.parser')

title = bs_template.find('title')
title.string = "TTTTT"
div_container = bs_template.find("div", {"class": "container"})
div_container.string = "XXXXXXXXXXXXXXXXXXXX"

# for div_container in bs_template.find_all("div", {"class": "container"}):
#     div_container.string = "XXXXX"

print(bs_template)

<!DOCTYPE html>

<html lang="en">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<base href="https://changwhaj.github.io/assets/"/>
</head>
<body class="home2"><div style="position:relative;">
<!-- RubyOnRails - formstatic / kaminari -->
<meta content="authenticity_token" name="csrf-param"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-119892649-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-119892649-1');
</script>
<!-- meta tag -->
<meta charset="utf-8"/>
<title>TTTTT</title>
<!-- responsive tag -->
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- favicon -->
<link href="/assets/images/et/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/assets/images/et/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/assets/images/et/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/assets/images/et/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/assets/images/et/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/assets/images/et/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/assets/images/et/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/assets/images/et/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/assets/images/et/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/assets/images/et/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/assets/images/et/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/assets/images/et/favicon/manifest.json" rel="manifest"/>
<meta content="#007bff" name="msapplication-TileColor"/>
<meta content="/assets/images/et/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- deflink == defered link (loaded later by jquery) -->
<!-- bootstrap v4 css -->
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<!-- font-awesome css -->
<link defhref="/assets/css/font-awesome.min.css" href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<!-- animate css -->
<link defhref="/assets/css/animate.css" href="/assets/css/animate.css" rel="stylesheet" type="text/css"/>
<!-- owl.carousel css -->
<link defhref="/assets/css/owl.carousel.css" href="/assets/css/owl.carousel.css" rel="stylesheet" type="text/css"/>
<!-- slick css -->
<link defhref="/assets/css/slick.css" href="/assets/css/slick.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu CSS -->
<link href="/assets/css/rsmenu-main.css" rel="stylesheet" type="text/css"/>
<!-- rsmenu transitions CSS -->
<link defhref="/assets/css/rsmenu-transitions.css" href="/assets/css/rsmenu-transitions.css" rel="stylesheet" type="text/css"/>
<!-- magnific popup css -->
<link defhref="/assets/css/magnific-popup.css" href="/assets/css/magnific-popup.css" rel="stylesheet" type="text/css"/>
<!-- flaticon css  -->
<link defhref="/assets/fonts/flaticon.css" href="/assets/fonts/flaticon.css" rel="stylesheet" type="text/css"/>
<!-- flaticon2 css  -->
<link defhref="/assets/fonts/fonts2/flaticon.css" href="/assets/fonts/fonts2/flaticon.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/style.css?ver=1" rel="stylesheet" type="text/css"/>
<link href="/assets/css/color/default.css" rel="stylesheet" type="text/css"/>
<!-- responsive css -->
<link href="/assets/css/responsive.css" rel="stylesheet" type="text/css"/>
<meta content="”NOARCHIVE”" name="”ROBOTS”"/>
<link href="/assets/css/forum.css" rel="stylesheet" type="text/css"/>
<style>
</style>
<div class="sec-spacer pt-50">
<div class="container">XXXXXXXXXXXXXXXXXXXX</div>
</div>
<!-- start scrollUp  -->
<div class="d-print-none" id="scrollUp">
<i class="fa fa-angle-up"></i>
</div>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- modernizr js -->
<script src="/assets/js/modernizr-2.8.3.min.js"></script>
<!-- jquery latest version -->
<script src="/assets/js/jquery.min.js"></script>
<!-- bootstrap js -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- owl.carousel js
        <script src="/assets/js/owl.carousel.min.js"></script>-->
<!-- slick.min js -->
<script src="/assets/js/slick.min.js"></script>
<!-- isotope.pkgd.min js -->
<script src="/assets/js/isotope.pkgd.min.js"></script>
<!-- imagesloaded.pkgd.min js -->
<script src="/assets/js/imagesloaded.pkgd.min.js"></script>
<!-- wow js -->
<script src="/assets/js/wow.min.js"></script>
<!-- counter top js -->
<script src="/assets/js/waypoints.min.js"></script>
<script src="/assets/js/jquery.counterup.min.js"></script>
<!-- magnific popup -->
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<!-- rsmenu js -->
<script src="/assets/js/rsmenu-main.js"></script>
<!-- plugins js -->
<script src="/assets/js/plugins.js"></script>
<!-- Switch js -->
<script src="/assets/js/color-style.js"></script>
<!-- main js -->
<script src="/assets/js/main.js"></script>
<script src="/assets/js/bootbox.min.js"></script>
<script async="" defer="" src="/assets/js/bootstrap3-typeahead.min.js">
</script>
<script type="text/javascript">
    // Activate tooltips
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    })

    $(document).ready(function () {
        // Load stylesheets in a deferred way:
        $('link[defhref]').each(function() {
            $(this).attr('href', $(this).attr('defhref'));
            //var src = $(this).attr('href');
            //loadStyleSheet(src);
        });

        // Load mobile images in a deferred way:
        var isMobile = window.matchMedia("only screen and (max-width: 490px)").matches;
        if (isMobile) {
            $('img[mobile-defsrc]').each(function () {
                $(this).attr('src', $(this).attr('mobile-defsrc')).removeAttr('defsrc');
            });
        }

        // Load images in a deferred way:
        $('img[defsrc]').each(function() {
            $(this).attr('src',$(this).attr('defsrc'));
        });


        function delayedStart() {
            // Typeahead start

            // Register typeahead element:
            $('#header-keyword-search, #modal-keyword-search').typeahead({
                source: autoCompleteQuery,
                autoSelect: true,
                delay: 150,
                selectOnBlur: false,
                afterSelect: function(param) {$(this.$element).closest('form').submit()}
            });

            // Query ajax function:
            function autoCompleteQuery(query, callback) {
                return $.get("/ajax/autocomplete/suggestions/?query=" + query).done(callback);
            }
            // Typeahead end
        }
        setTimeout(delayedStart, 1500);

        // Don't submit empty search query
        $('#modal-keyword-search-form').submit(function() {
            if (!$('#modal-keyword-search').val()) {
                return false;
            }
        });

        // Auto focus on search box when search-modal is opened
        $('.search-modal').on('shown.bs.modal', function (e) {
            $(this).find('input[type=text]').focus();
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function (){
        set_voting_configuration_by_question($(".question-body"));
    });
</script>
<input class="csrf-value" type="hidden" value=""/><!-- Moderate actions: -->
<script type="text/javascript">
    // Approve:
    $("body").on("click", ".approve-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "approve");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else {
            $(this).closest(".media").find(".approve-comment-button").slideUp();
            $(this).closest(".media").find(".comment-head-notification").text("");
        }
    });

    // Delete:
    $("body").on("click", ".delete-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "delete");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Bump:
    $("body").on("click", ".bump-comment-button", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        moderate_comment(comment_id, "bump");
        if ($(this).closest(".comment-moderation-row").length)
            $(this).closest(".comment-moderation-row").slideUp().remove();
        else
            $(this).closest(".media").slideUp().remove();
    });

    // Edit open:
    $("body").on("click", ".edit-comment-button", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var comment_original_text = comment_content_div.text();

        var edit_comment_content = $("#edit-comment-template").html();

        comment_content_div.text("");
        comment_content_div.html(edit_comment_content);

        comment_content_div.find(".original-comment").text(comment_original_text);
        textarea = comment_content_div.find("textarea")
        textarea.text(comment_original_text);
        autoresize(textarea);
    });

    // Edit cancel:
    $("body").on("click", ".comment-edit-cancel", function (e) {
        e.preventDefault();
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var original_comment_content = comment_content_div.find(".original-comment").text();
        comment_content_div.html(original_comment_content);
    });

    // Edit save:
    $("body").on("click", ".comment-edit-save", function (e) {
        e.preventDefault();
        var comment_id = $(this).closest(".media").attr("data-comment-id");
        var comment_content_div = $(this).closest(".media").find(".comment-content").first();
        var new_comment_content = comment_content_div.find("textarea").val();

        moderate_comment(comment_id, "edit", new_comment_content);
        comment_content_div.html(new_comment_content);
    });

    function moderate_comment(comment_id, action, extra) {
        if (extra === undefined) {
            extra = 1;
        }
        var ajax_data = {
            'comment_id': comment_id,
        };
        ajax_data[action] = extra;

        $.ajax({
            url: "/ajax/moderate/",
            method: 'GET',
            data: ajax_data,
            error: function (xhr, status, error) {
                alert(status.toString() + "," + error.toString() + ":" + xhr.responseText);
            }
        });
    }

    // Auto resize textarea to fit contents:
    function autoresize(textarea) {
        textarea = $(textarea)
        textarea.css('height','0px');     //Reset height, so that it not only grows but also shrinks
        textarea.css('height',(textarea[0].scrollHeight + 10) + 'px');    //Set new height
    }

    $('textarea.comment-edit').keyup(function () {
        autoresize(this);
    });

    // Handle "Load Full Discussion" button
    $("body").on("click", ".load-full-discussion-button", function (){
        if ($(this).hasClass("disabled"))
            return false;
        $(".load-full-discussion-button").addClass("disabled");
        let after_comment_id = $(this).parents(".load-more-section").data("after-comment");
        let discussion_id = $(this).parents(".load-more-section").data("discussion-id");
        let discussion_load_indicator = $('.full-discussion-loading-spinner').clone()
        let discussion_container = $(this).parents(".outer-discussion-container");
        $(this).replaceWith(discussion_load_indicator);
        discussion_load_indicator.show();

        $.ajax({
            url: "/ajax/discussion/load-complete/",
            method: 'GET',
            dataType: 'html',
            data: {"discussion-id": discussion_id},
            success: function (full_discussion_html) {
                let full_discusssion = $(full_discussion_html);
                discussion_container.replaceWith(full_discusssion);
                // Scroll to the current comment location:
                setTimeout(function() {
                    $(document).scrollTop(
                        $("#comment-"+after_comment_id).offset().top - 80
                    )
                }, 100);
            },
            error: function (xhr, status, error) {
                alert("Error loading full discussion");
            }
        })
    });
</script>
<script src="/assets/js/comments.js?ver=1" type="text/javascript"></script>
<!-- / Comments dependencies -->
<script src="/assets/js/examview.js?ver=4" type="text/javascript"></script>
<!-- End temporary -->
<input class="is-logged-in" type="hidden" value="0"/>
</div></body></html>

In [ ]:
format(int("812"), '04')

'0812'

In [ ]:
    driver.quit()

In [ ]:
def open_exam(driver, pageno):
    exam_url = 'http://webcache.googleusercontent.com/search?q=cache:' + \
                'https://www.examtopics.com/exams/amazon/aws-certified-database-specialty/view/' + str(pageno) + '/'
    # discuss_url = 'https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id=35981'
    page = driver.get(exam_url)
    time.sleep(randint(1, 10))
    return

def open_amazondiscuss(driver, pageno):
    discuss_url = \ # 'http://webcache.googleusercontent.com/search?q=cache:' + \
                'https://www.examtopics.com/discussions/amazon/' + str(pageno) + '/'
    # discuss_url = 'https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id=35981'
    page = driver.get(discuss_url)
    time.sleep(randint(1, 10))
    return


def remove_element(driver, pageno):
    driver.execute_script("return document.getElementsByClassName('btn btn-success')[0].setAttribute('href','exam/aws/DBS/page/DBS-P" + str(pageno - 1) + ".html');")
    driver.execute_script("return document.getElementsByClassName('btn btn-success pull-right')[0].setAttribute('href','exam/aws/DBS/page/DBS-P" + str(pageno + 1) + ".html');")
    for i in range(4):
        try:
            driver.execute_script("return document.getElementsByClassName('btn btn-secondary question-discussion-button d-print-none')[" + str(i) + "].setAttribute('href','exam/aws/DBS/DBS-Q" + ('%03d' % ((pageno-1)*4 + i + 1)) + ".html');")
        except:
            continue

    driver.execute_script("""
        function getElementByXpath(path) {
            return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
        }
        function removeElement(element) {
            if (element !== undefined) {
                element.remove();
            }
        }
        function removeElemAttr(element, attr) {
            if (element !== undefined && element !== null) {
                element.removeAttribute(attr);
            }
        }
        removeElement(document.getElementById('bN015htcoyT__google-cache-hdr'));
        removeElement(getElementByXpath("/html/head/style"));
        removeElement(document.getElementsByClassName('full-width-header')[0]);
        removeElement(document.getElementsByClassName('exam-view-header')[0]);
        removeElement(document.getElementsByClassName('row')[0]);
        removeElement(document.getElementById('rs-footer'));
        getElementByXpath("/html/head/base").setAttribute('href','https://changwhaj.github.io/assets/');
        getElementByXpath("/html").removeAttribute("class");
        // document.getElementsByClassName('btn btn-success')[0].setAttribute('href','/exam/AWS/DBS/DBS-P1.html');
        // document.getElementsByClassName('btn btn-success pull-right')[0].setAttribute('href','/exam/AWS/DBS/DBS-P3.html');

        // removeElement(document.getElementsByClassName('page-navigation-bar')[0]);
        removeElement(document.getElementById('engagement-modal'));
        removeElement(document.getElementsByClassName('modal-backdrop show')[1]);
        removeElement(document.getElementsByClassName('modal-backdrop show')[0]);
        getElementByXpath("/html/body/base").removeAttribute("href");
        return;
    """)

def save_html(driver, fname):
    html = driver.page_source
    bs = BeautifulSoup(html, 'html.parser')
    print(fname)
    with open(fname, "w", encoding='utf-8') as file:
        file.write('<!DOCTYPE html>\n' + str(bs))

SyntaxError: unexpected character after line continuation character (Temp/ipykernel_20368/3573070062.py, line 10)

In [ ]:
if __name__ == "__main__":
    driver = webdriver.Chrome('c:/temp/chromedriver.exe')

    for i in range(47)[40:45]:
        pageno = i + 1
        fname = 'DBS/page/DBS-P' + str(pageno) + '.html'
        print(fname)

        my_file = Path(fname)
        if my_file.is_file():
            # file exists
            continue

        try:
            open_exam(driver, pageno)
            driver.switch_to.window(driver.window_handles[0])
            print(driver.title)
            if (driver.title == 'Error 404 (Not Found)!!1'):
                with open(fname, "w", encoding='utf-8') as file:
                    file.write('Error 404 (Not Found)')
                continue

            remove_element(driver, pageno)

        except:
            time.sleep(randint(1, 20))
            pass

        finally:
            save_html(driver, fname)
        
    driver.quit()

In [ ]:
    driver = webdriver.Chrome('c:/temp/chromedriver.exe')

In [ ]:
pageno = 1
fname = 'DBS/page/DBS-P' + str(pageno) + '.html'
my_file = Path(fname)
print(fname)
if my_file.is_file():
    # file exists
    print(fname)

DBS/page/DBS-P1.html

In [ ]:
open_exam(driver, 6)

In [ ]:
driver.switch_to.window(driver.window_handles[0])
print(driver.title)

AWS Certified Database - Specialty Exam – Free Exam Q&As, Page 5 | ExamTopics

In [ ]:
body > div.sec-spacer > div > div:nth-child(3) > div > div
    /html/body/div[2]/div/div[3]/div/div
container-fluid discussion-list

In [ ]:
driver.switch_to.window(driver.window_handles[0])
print(driver.title)
bs = BeautifulSoup(driver.page_source, 'html.parser')
div_card = bs.find_all("div", {"class": "container-fluid discussion-list"})
a = bs.find_all("a", {"class": "discussion-link"})
for i in range(len(a)):
    print(a[i]["href"])

Amazon discussions - ExamTopics Forum
/discussions/amazon/view/48843-exam-aws-certified-database-specialty-topic-1-question-140/
/discussions/amazon/view/46764-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/68751-exam-aws-certified-developer-associate-topic-1-question-372/
/discussions/amazon/view/65738-exam-aws-certified-database-specialty-topic-1-question-157/
/discussions/amazon/view/51710-exam-aws-certified-data-analytics-specialty-topic-1-question/
/discussions/amazon/view/49205-exam-aws-certified-database-specialty-topic-1-question-104/
/discussions/amazon/view/35803-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/27770-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/49007-exam-aws-certified-database-specialty-topic-1-question-126/
/discussions/amazon/view/65925-exam-aws-certified-database-specialty-topic-1-question-162/
/discussions/amazon/view/74242-exam-aws-certified-data-analytics-specialty-topic-1-question/
/discussions/amazon/view/61062-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/73977-exam-aws-certified-machine-learning-specialty-topic-1/
/discussions/amazon/view/2374-exam-aws-devops-engineer-professional-topic-1-question-44/
/discussions/amazon/view/4255-exam-aws-certified-developer-associate-topic-1-question-136/
/discussions/amazon/view/4776-exam-aws-certified-developer-associate-topic-1-question-201/
/discussions/amazon/view/68931-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/46839-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/27700-exam-aws-certified-solutions-architect-associate-saa-c02/
/discussions/amazon/view/6150-exam-aws-certified-developer-associate-topic-1-question-154/

In [ ]:
    driver = webdriver.Chrome('c:/temp/chromedriver.exe')
    
    fname = 'AmazonDiscussList.html'
    print(fname)

    my_file = Path(fname)

AmazonDiscussList.html

In [ ]:
def open_amazondiscuss(driver, pageno):
    discuss_url = 'https://www.examtopics.com/discussions/amazon/' + str(pageno) + '/'
    # discuss_url = 'https://www.examtopics.com/ajax/discussion/load-complete/?discussion-id=35981'
    page = driver.get(discuss_url)
    time.sleep(randint(1, 10))
    return

In [ ]:
#pageno = 2
#open_amazondiscuss(driver, pageno)
driver.switch_to.window(driver.window_handles[0])
print(driver.title + "-" + str(pageno))
bs = BeautifulSoup(driver.page_source, 'html.parser')
a = bs.find_all("a", {"class": "btn btn-secondary question-discussion-button d-print-none"})
for i in range(len(a)):
    print(a[i]["href"])

AWS Certified Cloud Practitioner Exam – Free Exam Q&As, Page 37 | ExamTopics-375
/discussions/amazon/view/20816-exam-aws-certified-cloud-practitioner-topic-1-question-166/
/discussions/amazon/view/6955-exam-aws-certified-cloud-practitioner-topic-1-question-42/
/discussions/amazon/view/44218-exam-aws-certified-cloud-practitioner-topic-1-question-526/
#
#
/discussions/amazon/view/17028-exam-aws-certified-cloud-practitioner-topic-1-question-116/
/discussions/amazon/view/44217-exam-aws-certified-cloud-practitioner-topic-1-question-527/
/discussions/amazon/view/26020-exam-aws-certified-cloud-practitioner-topic-1-question-240/
/discussions/amazon/view/35036-exam-aws-certified-cloud-practitioner-topic-1-question-486/
/discussions/amazon/view/33445-exam-aws-certified-cloud-practitioner-topic-1-question-464/

In [ ]:
a = bs.find_all("a", {"class": "discussion-link"})
a[0].text.strip()

'Exam AWS Certified Solutions Architect - Associate SAA-C02 topic 1 question 791 discussion'

In [ ]:
with open("AmazonDiscussList.txt", "w", encoding='utf-8') as file:    
    for i in range(375):
        pageno = i + 1

        open_amazondiscuss(driver, pageno)

        driver.switch_to.window(driver.window_handles[0])
        print(driver.title + "-" + str(pageno))
        bs = BeautifulSoup(driver.page_source, 'html.parser')
        div_card = bs.find_all("div", {"class": "container-fluid discussion-list"})
        a = bs.find_all("a", {"class": "discussion-link"})
        for i in range(len(a)):
            file.write(str(a[i].text.strip())+"\t")
            file.write(str(a[i]["href"])+"\n")
            
file.close()

Amazon discussions - ExamTopics Forum-1
Amazon discussions - ExamTopics Forum-2
Amazon discussions - ExamTopics Forum-3
Amazon discussions - ExamTopics Forum-4
Amazon discussions - ExamTopics Forum-5
Amazon discussions - ExamTopics Forum-6
Amazon discussions - ExamTopics Forum-7
Amazon discussions - ExamTopics Forum-8
Amazon discussions - ExamTopics Forum-9
Amazon discussions - ExamTopics Forum-10
Amazon discussions - ExamTopics Forum-11
Amazon discussions - ExamTopics Forum-12
Amazon discussions - ExamTopics Forum-13
Amazon discussions - ExamTopics Forum-14
Amazon discussions - ExamTopics Forum-15
Amazon discussions - ExamTopics Forum-16
Amazon discussions - ExamTopics Forum-17
Amazon discussions - ExamTopics Forum-18
Amazon discussions - ExamTopics Forum-19
Amazon discussions - ExamTopics Forum-20
Amazon discussions - ExamTopics Forum-21
Amazon discussions - ExamTopics Forum-22
Amazon discussions - ExamTopics Forum-23
Amazon discussions - ExamTopics Forum-24
Amazon discussions - ExamTopics Forum-25
Amazon discussions - ExamTopics Forum-26
Amazon discussions - ExamTopics Forum-27
Amazon discussions - ExamTopics Forum-28
Amazon discussions - ExamTopics Forum-29
Amazon discussions - ExamTopics Forum-30
Amazon discussions - ExamTopics Forum-31
Amazon discussions - ExamTopics Forum-32
Amazon discussions - ExamTopics Forum-33
Amazon discussions - ExamTopics Forum-34
Amazon discussions - ExamTopics Forum-35
Amazon discussions - ExamTopics Forum-36
Amazon discussions - ExamTopics Forum-37
Amazon discussions - ExamTopics Forum-38
Amazon discussions - ExamTopics Forum-39
Amazon discussions - ExamTopics Forum-40
Amazon discussions - ExamTopics Forum-41
Amazon discussions - ExamTopics Forum-42
Amazon discussions - ExamTopics Forum-43
Amazon discussions - ExamTopics Forum-44
Amazon discussions - ExamTopics Forum-45
Amazon discussions - ExamTopics Forum-46
Amazon discussions - ExamTopics Forum-47
Amazon discussions - ExamTopics Forum-48
Amazon discussions - ExamTopics Forum-49
Amazon discussions - ExamTopics Forum-50
Amazon discussions - ExamTopics Forum-51
Amazon discussions - ExamTopics Forum-52
Amazon discussions - ExamTopics Forum-53
Amazon discussions - ExamTopics Forum-54
Amazon discussions - ExamTopics Forum-55
Amazon discussions - ExamTopics Forum-56
Amazon discussions - ExamTopics Forum-57
Amazon discussions - ExamTopics Forum-58
Amazon discussions - ExamTopics Forum-59
Amazon discussions - ExamTopics Forum-60
Amazon discussions - ExamTopics Forum-61
Amazon discussions - ExamTopics Forum-62
Amazon discussions - ExamTopics Forum-63
Amazon discussions - ExamTopics Forum-64
Amazon discussions - ExamTopics Forum-65
Amazon discussions - ExamTopics Forum-66
Amazon discussions - ExamTopics Forum-67
Amazon discussions - ExamTopics Forum-68
Amazon discussions - ExamTopics Forum-69
Amazon discussions - ExamTopics Forum-70
Amazon discussions - ExamTopics Forum-71
Amazon discussions - ExamTopics Forum-72
Amazon discussions - ExamTopics Forum-73
Amazon discussions - ExamTopics Forum-74
Amazon discussions - ExamTopics Forum-75
Amazon discussions - ExamTopics Forum-76
Amazon discussions - ExamTopics Forum-77
Amazon discussions - ExamTopics Forum-78
Amazon discussions - ExamTopics Forum-79
Amazon discussions - ExamTopics Forum-80
Amazon discussions - ExamTopics Forum-81
Amazon discussions - ExamTopics Forum-82
Amazon discussions - ExamTopics Forum-83
Amazon discussions - ExamTopics Forum-84
Amazon discussions - ExamTopics Forum-85
Amazon discussions - ExamTopics Forum-86
Amazon discussions - ExamTopics Forum-87
Amazon discussions - ExamTopics Forum-88
Amazon discussions - ExamTopics Forum-89
Amazon discussions - ExamTopics Forum-90
Amazon discussions - ExamTopics Forum-91
Amazon discussions - ExamTopics Forum-92
Amazon discussions - ExamTopics Forum-93
Amazon discussions - ExamTopics Forum-94
Amazon discussions - ExamTopics Forum-95
Amazon discussions - ExamTopics Forum-96
Amazon discussions - ExamTopics Forum-97
Amazon discussions - ExamTopics Forum-98
Amazon discussions - ExamTopics Forum-99
Amazon discussions - ExamTopics Forum-100
Amazon discussions - ExamTopics Forum-101
Amazon discussions - ExamTopics Forum-102
Amazon discussions - ExamTopics Forum-103
Amazon discussions - ExamTopics Forum-104
Amazon discussions - ExamTopics Forum-105
Amazon discussions - ExamTopics Forum-106
Amazon discussions - ExamTopics Forum-107
Amazon discussions - ExamTopics Forum-108
Amazon discussions - ExamTopics Forum-109
Amazon discussions - ExamTopics Forum-110
Amazon discussions - ExamTopics Forum-111
Amazon discussions - ExamTopics Forum-112
Amazon discussions - ExamTopics Forum-113
Amazon discussions - ExamTopics Forum-114
Amazon discussions - ExamTopics Forum-115
Amazon discussions - ExamTopics Forum-116
Amazon discussions - ExamTopics Forum-117
Amazon discussions - ExamTopics Forum-118
Amazon discussions - ExamTopics Forum-119
Amazon discussions - ExamTopics Forum-120
Amazon discussions - ExamTopics Forum-121
Amazon discussions - ExamTopics Forum-122
Amazon discussions - ExamTopics Forum-123
Amazon discussions - ExamTopics Forum-124
Amazon discussions - ExamTopics Forum-125
Amazon discussions - ExamTopics Forum-126
Amazon discussions - ExamTopics Forum-127
Amazon discussions - ExamTopics Forum-128
Amazon discussions - ExamTopics Forum-129
Amazon discussions - ExamTopics Forum-130
Amazon discussions - ExamTopics Forum-131
Amazon discussions - ExamTopics Forum-132
Amazon discussions - ExamTopics Forum-133
Amazon discussions - ExamTopics Forum-134
Amazon discussions - ExamTopics Forum-135
Amazon discussions - ExamTopics Forum-136
Amazon discussions - ExamTopics Forum-137
Amazon discussions - ExamTopics Forum-138
Amazon discussions - ExamTopics Forum-139
Amazon discussions - ExamTopics Forum-140
Amazon discussions - ExamTopics Forum-141
Amazon discussions - ExamTopics Forum-142
Amazon discussions - ExamTopics Forum-143
Amazon discussions - ExamTopics Forum-144
Amazon discussions - ExamTopics Forum-145
Amazon discussions - ExamTopics Forum-146
Amazon discussions - ExamTopics Forum-147
Amazon discussions - ExamTopics Forum-148
Amazon discussions - ExamTopics Forum-149
Amazon discussions - ExamTopics Forum-150
Amazon discussions - ExamTopics Forum-151
Amazon discussions - ExamTopics Forum-152
Amazon discussions - ExamTopics Forum-153
Amazon discussions - ExamTopics Forum-154
Amazon discussions - ExamTopics Forum-155
Amazon discussions - ExamTopics Forum-156
Amazon discussions - ExamTopics Forum-157
Amazon discussions - ExamTopics Forum-158
Amazon discussions - ExamTopics Forum-159
Amazon discussions - ExamTopics Forum-160
Amazon discussions - ExamTopics Forum-161
Amazon discussions - ExamTopics Forum-162
Amazon discussions - ExamTopics Forum-163
Amazon discussions - ExamTopics Forum-164
Amazon discussions - ExamTopics Forum-165
Amazon discussions - ExamTopics Forum-166
Amazon discussions - ExamTopics Forum-167
Amazon discussions - ExamTopics Forum-168
Amazon discussions - ExamTopics Forum-169
Amazon discussions - ExamTopics Forum-170
Amazon discussions - ExamTopics Forum-171
Amazon discussions - ExamTopics Forum-172
Amazon discussions - ExamTopics Forum-173
Amazon discussions - ExamTopics Forum-174
Amazon discussions - ExamTopics Forum-175
Amazon discussions - ExamTopics Forum-176
Amazon discussions - ExamTopics Forum-177
Amazon discussions - ExamTopics Forum-178
Amazon discussions - ExamTopics Forum-179
Amazon discussions - ExamTopics Forum-180
Amazon discussions - ExamTopics Forum-181
Amazon discussions - ExamTopics Forum-182
Amazon discussions - ExamTopics Forum-183
Amazon discussions - ExamTopics Forum-184
Amazon discussions - ExamTopics Forum-185
Amazon discussions - ExamTopics Forum-186
Amazon discussions - ExamTopics Forum-187
Amazon discussions - ExamTopics Forum-188
Amazon discussions - ExamTopics Forum-189
Amazon discussions - ExamTopics Forum-190
Amazon discussions - ExamTopics Forum-191
Amazon discussions - ExamTopics Forum-192
Amazon discussions - ExamTopics Forum-193
Amazon discussions - ExamTopics Forum-194
Amazon discussions - ExamTopics Forum-195
Amazon discussions - ExamTopics Forum-196
Amazon discussions - ExamTopics Forum-197
Amazon discussions - ExamTopics Forum-198

Amazon discussions - ExamTopics Forum-199
Amazon discussions - ExamTopics Forum-200
Amazon discussions - ExamTopics Forum-201
Amazon discussions - ExamTopics Forum-202
Amazon discussions - ExamTopics Forum-203
Amazon discussions - ExamTopics Forum-204
Amazon discussions - ExamTopics Forum-205
Amazon discussions - ExamTopics Forum-206
Amazon discussions - ExamTopics Forum-207
Amazon discussions - ExamTopics Forum-208
Amazon discussions - ExamTopics Forum-209
Amazon discussions - ExamTopics Forum-210
Amazon discussions - ExamTopics Forum-211
Amazon discussions - ExamTopics Forum-212
Amazon discussions - ExamTopics Forum-213
Amazon discussions - ExamTopics Forum-214
Amazon discussions - ExamTopics Forum-215
Amazon discussions - ExamTopics Forum-216
Amazon discussions - ExamTopics Forum-217
Amazon discussions - ExamTopics Forum-218
Amazon discussions - ExamTopics Forum-219
Amazon discussions - ExamTopics Forum-220
Amazon discussions - ExamTopics Forum-221
Amazon discussions - ExamTopics Forum-222
Amazon discussions - ExamTopics Forum-223
Amazon discussions - ExamTopics Forum-224
Amazon discussions - ExamTopics Forum-225
Amazon discussions - ExamTopics Forum-226
Amazon discussions - ExamTopics Forum-227
Amazon discussions - ExamTopics Forum-228
Amazon discussions - ExamTopics Forum-229
Amazon discussions - ExamTopics Forum-230
Amazon discussions - ExamTopics Forum-231
Amazon discussions - ExamTopics Forum-232
Amazon discussions - ExamTopics Forum-233
Amazon discussions - ExamTopics Forum-234
Amazon discussions - ExamTopics Forum-235
Amazon discussions - ExamTopics Forum-236
Amazon discussions - ExamTopics Forum-237
Amazon discussions - ExamTopics Forum-238
Amazon discussions - ExamTopics Forum-239
Amazon discussions - ExamTopics Forum-240
Amazon discussions - ExamTopics Forum-241
Amazon discussions - ExamTopics Forum-242
Amazon discussions - ExamTopics Forum-243
Amazon discussions - ExamTopics Forum-244
Amazon discussions - ExamTopics Forum-245
Amazon discussions - ExamTopics Forum-246
Amazon discussions - ExamTopics Forum-247
Amazon discussions - ExamTopics Forum-248
Amazon discussions - ExamTopics Forum-249
Amazon discussions - ExamTopics Forum-250
Amazon discussions - ExamTopics Forum-251
Amazon discussions - ExamTopics Forum-252
Amazon discussions - ExamTopics Forum-253
Amazon discussions - ExamTopics Forum-254
Amazon discussions - ExamTopics Forum-255
Amazon discussions - ExamTopics Forum-256
Amazon discussions - ExamTopics Forum-257
Amazon discussions - ExamTopics Forum-258
Amazon discussions - ExamTopics Forum-259
Amazon discussions - ExamTopics Forum-260
Amazon discussions - ExamTopics Forum-261
Amazon discussions - ExamTopics Forum-262
Amazon discussions - ExamTopics Forum-263
Amazon discussions - ExamTopics Forum-264
Amazon discussions - ExamTopics Forum-265
Amazon discussions - ExamTopics Forum-266
Amazon discussions - ExamTopics Forum-267
Amazon discussions - ExamTopics Forum-268
Amazon discussions - ExamTopics Forum-269
Amazon discussions - ExamTopics Forum-270
Amazon discussions - ExamTopics Forum-271
Amazon discussions - ExamTopics Forum-272
Amazon discussions - ExamTopics Forum-273
Amazon discussions - ExamTopics Forum-274
Amazon discussions - ExamTopics Forum-275
Amazon discussions - ExamTopics Forum-276
Amazon discussions - ExamTopics Forum-277
Amazon discussions - ExamTopics Forum-278
Amazon discussions - ExamTopics Forum-279
Amazon discussions - ExamTopics Forum-280
Amazon discussions - ExamTopics Forum-281
Amazon discussions - ExamTopics Forum-282
Amazon discussions - ExamTopics Forum-283
Amazon discussions - ExamTopics Forum-284
Amazon discussions - ExamTopics Forum-285
Amazon discussions - ExamTopics Forum-286
Amazon discussions - ExamTopics Forum-287
Amazon discussions - ExamTopics Forum-288
Amazon discussions - ExamTopics Forum-289
Amazon discussions - ExamTopics Forum-290
Amazon discussions - ExamTopics Forum-291
Amazon discussions - ExamTopics Forum-292
Amazon discussions - ExamTopics Forum-293
Amazon discussions - ExamTopics Forum-294
Amazon discussions - ExamTopics Forum-295
Amazon discussions - ExamTopics Forum-296
Amazon discussions - ExamTopics Forum-297
Amazon discussions - ExamTopics Forum-298
Amazon discussions - ExamTopics Forum-299
Amazon discussions - ExamTopics Forum-300
Amazon discussions - ExamTopics Forum-301
Amazon discussions - ExamTopics Forum-302
Amazon discussions - ExamTopics Forum-303
Amazon discussions - ExamTopics Forum-304
Amazon discussions - ExamTopics Forum-305
Amazon discussions - ExamTopics Forum-306
Amazon discussions - ExamTopics Forum-307
Amazon discussions - ExamTopics Forum-308
Amazon discussions - ExamTopics Forum-309
Amazon discussions - ExamTopics Forum-310
Amazon discussions - ExamTopics Forum-311
Amazon discussions - ExamTopics Forum-312
Amazon discussions - ExamTopics Forum-313
Amazon discussions - ExamTopics Forum-314
Amazon discussions - ExamTopics Forum-315
Amazon discussions - ExamTopics Forum-316
Amazon discussions - ExamTopics Forum-317
Amazon discussions - ExamTopics Forum-318
Amazon discussions - ExamTopics Forum-319
Amazon discussions - ExamTopics Forum-320
Amazon discussions - ExamTopics Forum-321
Amazon discussions - ExamTopics Forum-322
Amazon discussions - ExamTopics Forum-323
Amazon discussions - ExamTopics Forum-324
Amazon discussions - ExamTopics Forum-325
Amazon discussions - ExamTopics Forum-326
Amazon discussions - ExamTopics Forum-327
Amazon discussions - ExamTopics Forum-328
Amazon discussions - ExamTopics Forum-329
Amazon discussions - ExamTopics Forum-330
Amazon discussions - ExamTopics Forum-331
Amazon discussions - ExamTopics Forum-332
Amazon discussions - ExamTopics Forum-333
Amazon discussions - ExamTopics Forum-334
Amazon discussions - ExamTopics Forum-335
Amazon discussions - ExamTopics Forum-336
Amazon discussions - ExamTopics Forum-337
Amazon discussions - ExamTopics Forum-338
Amazon discussions - ExamTopics Forum-339
Amazon discussions - ExamTopics Forum-340
Amazon discussions - ExamTopics Forum-341
Amazon discussions - ExamTopics Forum-342
Amazon discussions - ExamTopics Forum-343
Amazon discussions - ExamTopics Forum-344
Amazon discussions - ExamTopics Forum-345
Amazon discussions - ExamTopics Forum-346
Amazon discussions - ExamTopics Forum-347
Amazon discussions - ExamTopics Forum-348
Amazon discussions - ExamTopics Forum-349
Amazon discussions - ExamTopics Forum-350
Amazon discussions - ExamTopics Forum-351
Amazon discussions - ExamTopics Forum-352
Amazon discussions - ExamTopics Forum-353
Amazon discussions - ExamTopics Forum-354
Amazon discussions - ExamTopics Forum-355
Amazon discussions - ExamTopics Forum-356
Amazon discussions - ExamTopics Forum-357
Amazon discussions - ExamTopics Forum-358
Amazon discussions - ExamTopics Forum-359
Amazon discussions - ExamTopics Forum-360
Amazon discussions - ExamTopics Forum-361
Amazon discussions - ExamTopics Forum-362
Amazon discussions - ExamTopics Forum-363
Amazon discussions - ExamTopics Forum-364
Amazon discussions - ExamTopics Forum-365
Amazon discussions - ExamTopics Forum-366
Amazon discussions - ExamTopics Forum-367
Amazon discussions - ExamTopics Forum-368
Amazon discussions - ExamTopics Forum-369
Amazon discussions - ExamTopics Forum-370
Amazon discussions - ExamTopics Forum-371
Amazon discussions - ExamTopics Forum-372
Amazon discussions - ExamTopics Forum-373
Amazon discussions - ExamTopics Forum-374
Amazon discussions - ExamTopics Forum-375

In [ ]:
driver.switch_to.window(driver.window_handles[0])
print(driver.title)

bs = BeautifulSoup(driver.page_source, 'html.parser')
div_questions = bs.find_all("div", {"class": "questions-container"})

with open("DBS_Page.html", "a", encoding='utf-8') as file:
    #file.append(div_questions)
    file.write(str(div_questions))

AWS Certified Database - Specialty Exam – Free Exam Q&As, Page 41 | ExamTopics

In [ ]:
    driver.execute_script("return document.getElementsByClassName('btn btn-success')[0].setAttribute('href','exam/aws/DBS/page/DBS-P" + str(pageno - 1) + ".html');")
    driver.execute_script("return document.getElementsByClassName('btn btn-success pull-right')[0].setAttribute('href','exam/aws/DBS/page/DBS-P" + str(pageno + 1) + ".html');")

In [1]:
import pyautogui

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.common.keys import Keys

from bs4 import BeautifulSoup

#from fake_useragent import UserAgent
from random import randrange
from datetime import datetime
import time

def set_chrome_driver():
    service = Service(executable_path=r'c:/temp/chromedriver.exe')
    userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)s Chrome/92.0.4515.131 Safari/537.36"
    options = webdriver.ChromeOptions()
    options.add_argument(f"user-agent={userAgent}")
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    options.add_argument('--no-sandbox')
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--lang=kr')  # set your language here
    driver = webdriver.Chrome(service=service, options=options)

    driver.set_window_size(1400, 1040)
    
    return driver

def set_translate_to_kr(driver):
    actionChains = ActionChains(driver)
    actionChains.context_click().perform()

    # here maybe problem. Debug it:
    for i in range(3):
        pyautogui.press('up')

    pyautogui.press('enter')
    pyautogui.sleep(1)

def scroll_page(driver):
    # Set the interval between scrolls in seconds
    scroll_interval = 1

    # Get the initial height of the page
    last_height = driver.execute_script("return document.body.scrollHeight")

    while True:
        # Send the down arrow key to scroll down the page
        driver.find_element(By.TAG_NAME, "body").send_keys(Keys.PAGE_DOWN)
        
        # Wait for the specified interval
        time.sleep(scroll_interval)
        
        # Calculate the new height of the page after scrolling
        new_height = driver.execute_script("return document.body.scrollHeight")
        
        # Check if the page has reached the end
        if new_height == last_height:
            break
        
        # Update the previous height
        last_height = new_height

def save_page(driver, fname):
    bs = BeautifulSoup(driver.page_source, 'html.parser')

    with open(fname, "w", encoding='utf-8') as file:
        file.write('<!DOCTYPE html>\n' + str(bs))
        # file.write(bs.prettify())

In [2]:
driver = set_chrome_driver()

for i in range(583)[35:37]:

    url = f'file:///C:/Users/Changwha/MyProjects/assets/assets/exam/aws/SAA_C03/SAA-Q{i+1:04}.html'
    fn = f'SAA_C03/kr/SAA-Q{i+1:04}-KR.html'
    try:
        driver.get(url)
        driver.switch_to.window(driver.window_handles[0])

        driver.find_element(By.CSS_SELECTOR, 'a.btn.btn-primary.reveal-solution').click()
        set_translate_to_kr(driver)
        driver.find_element(By.CSS_SELECTOR, 'a.btn.btn-primary.hide-solution').click()
        scroll_page(driver)
        driver.find_element(By.CSS_SELECTOR, '#scrollUp').click()
        time.sleep(1)
        driver.execute_script("arguments[0].remove();", driver.find_element(By.CSS_SELECTOR, '#goog-gt-tt'))
        driver.execute_script("arguments[0].remove();", driver.find_element(By.CSS_SELECTOR, 'head > link'))
        driver.execute_script("arguments[0].removeAttribute('class');", driver.find_element(By.TAG_NAME, 'html'))
        save_page(driver, fn)

    except Exception as e:
        print("Error:", str(e))
        print(f"*** Make question error !!! {e}")
        pass

driver.close()

In [95]:
driver.find_element(By.CSS_SELECTOR, 'a.btn.btn-primary.hide-solution').click()

In [96]:
driver.close()
# or webdriver.quit()

In [6]:
import re

str1='<div class="voting-summary col-12 col-sm-6 col-lg-4 pt-2 pb-2" style="font-size: 0.9em"><i>커뮤니티 투표 분배</i><!-- Additional optional vote button: <a href="javascript:void(0)" data-toggle="tooltip" class="vote-answer-button" title="Vote an answer">🗳️</a>--><div class="progress vote-distribution-bar"><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" class="vote-bar progress-bar bg-primary" data-original-title="6 votes." data-toggle="tooltip" role="progressbar" style="width: 100%; display: flex;" title="">B (100%)</div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-info" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">C (25%)'

pattern = r'<!-- Additional optional vote button: <a href="javascript:void(0)" data-toggle="tooltip" class="vote-answer-button" title="Vote an answer">🗳️</a>-->'
pattern = r'<!-- Additional optional vote button: <a href=.+</a>-->'
str2 = re.sub(pattern, '', str1)
print(str1)
print(str2)

<div class="voting-summary col-12 col-sm-6 col-lg-4 pt-2 pb-2" style="font-size: 0.9em"><i>커뮤니티 투표 분배</i><!-- Additional optional vote button: <a href="javascript:void(0)" data-toggle="tooltip" class="vote-answer-button" title="Vote an answer">🗳️</a>--><div class="progress vote-distribution-bar"><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" class="vote-bar progress-bar bg-primary" data-original-title="6 votes." data-toggle="tooltip" role="progressbar" style="width: 100%; display: flex;" title="">B (100%)</div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-info" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">C (25%)
<div class="voting-summary col-12 col-sm-6 col-lg-4 pt-2 pb-2" style="font-size: 0.9em"><i>커뮤니티 투표 분배</i><div class="progress vote-distribution-bar"><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" class="vote-bar progress-bar bg-primary" data-original-title="6 votes." data-toggle="tooltip" role="progressbar" style="width: 100%; display: flex;" title="">B (100%)</div><div aria-valuemax="100" aria-valuemin="0" aria-valuenow="30" class="vote-bar progress-bar bg-info" data-original-title="" data-toggle="tooltip" role="progressbar" style="width: 25%; display: none;" title="">C (25%)